CREATE TABLE `USR_LOOKUP_DYNAMIC_POM_POSITION_DECREMENT` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `POM_YEAR` varchar(45) NOT NULL,
  `LATEST_POSITION` varchar(30) NOT NULL,
  `SUBAPP` varchar(45) DEFAULT NULL,
  `YEARLY_DECREMENT` json NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE USR_LOOKUP_POM_POSITION(
	ID INT NOT NULL AUTO_INCREMENT,
    POM_YEAR VARCHAR(45) NOT NULL,
    LATEST_POSITION varchar(30) NOT NULL,
    IS_ACTIVE tinyint(1) NOT NULL DEFAULT 1,
    USER_ID INT NOT NULL,
    CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE USR_LOOKUP_POM_POSITION_CYCLE (
	  ID INT NOT NULL AUTO_INCREMENT,
    POM_YEAR VARCHAR(45) NOT NULL,
    CYCLE_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO USR_LOOKUP_POM_POSITION_CYCLE (POM_YEAR, CYCLE_ID, USER_ID) VALUES(2027, 1, 1);

CREATE TABLE `LOOKUP_POM_POSITION_DECREMENT` (
  `POSITION` varchar(30) DEFAULT NULL,
  `SUBAPP` varchar(30) DEFAULT NULL,
  `EXT_DECR` tinyint DEFAULT NULL,
  `ZBT_DECR` tinyint DEFAULT NULL,
  `ISS_DECR` tinyint DEFAULT NULL,
  `POM_DECR` tinyint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `LOOKUP_POM_POSITION_DECREMENT` (`POSITION`,`SUBAPP`,`EXT_DECR`,`ZBT_DECR`,`ISS_DECR`,`POM_DECR`) VALUES ('EXT','ZBT_SUMMARY',0,1,1,1);
INSERT INTO `LOOKUP_POM_POSITION_DECREMENT` (`POSITION`,`SUBAPP`,`EXT_DECR`,`ZBT_DECR`,`ISS_DECR`,`POM_DECR`) VALUES ('ZBT','ISS_SUMMARY',0,0,1,1);
INSERT INTO `LOOKUP_POM_POSITION_DECREMENT` (`POSITION`,`SUBAPP`,`EXT_DECR`,`ZBT_DECR`,`ISS_DECR`,`POM_DECR`) VALUES ('ISS','RESOURCE_CONSTRAINED_COA',0,0,0,1);
INSERT INTO `LOOKUP_POM_POSITION_DECREMENT` (`POSITION`,`SUBAPP`,`EXT_DECR`,`ZBT_DECR`,`ISS_DECR`,`POM_DECR`) VALUES ('POM',NULL,0,0,0,0);


INSERT INTO USR_LOOKUP_POM_POSITION (POM_YEAR, LATEST_POSITION, IS_ACTIVE, USER_ID)
VALUES(2027, 'EXT', 1, 1);
