
ALTER TABLE USR_LOOKUP_CRITERIA_WEIGHTS ADD CRITERIA_NAME_ID INT NOT NULL DEFAULT 1 AFTER WEIGHT_ID;
ALTER TABLE USR_OPTION_SCORES ADD CRITERIA_NAME_ID INT NOT NULL DEFAULT 1 AFTER ID;
ALTER TABLE USR_OPTION_SCORES DROP INDEX idx_user_id_option_id;
ALTER TABLE USR_OPTION_SCORES DROP INDEX idx_option_id_user_id_timestamp;
ALTER TABLE USR_OPTION_SCORES ADD UNIQUE INDEX idx_user_id_option_id(USER_ID, PROGRAM_ID, CRITERIA_NAME_ID);
ALTER TABLE USR_OPTION_SCORES ADD INDEX idx_option_id_user_id_timestamp(PROGRAM_ID, USER_ID, CRITERIA_NAME_ID, UPDATED_TIMESTAMP);
DROP TABLE USR_LOOKUP_OPTIMIZATION_RUNS;
ALTER TABLE USR_LOOKUP_SAVED_COA ADD CRITERIA_NAME_ID INT NOT NULL DEFAULT 1 AFTER ID;
ALTER TABLE USR_LOOKUP_USER_SAVED_COA ADD CRITERIA_NAME_ID INT NOT NULL DEFAULT 1 AFTER ID;
ALTER TABLE USR_ADMIN_USERS_HISTORY CHANGE `GROUP` `GROUP` VARCHAR(500);
ALTER TABLE USR_AO_AD_USERS_HISTORY CHANGE `GROUP` `GROUP` VARCHAR(500);
ALTER TABLE USR_ADMIN_USERS CHANGE `GROUP` `GROUP` enum('NONE','User Admin') NOT NULL DEFAULT 'NONE';
UPDATE USR_ADMIN_USERS SET `GROUP` = 'User Admin' WHERE `GROUP` = '';

CREATE TABLE IF NOT EXISTS `USR_LOOKUP_CYCLES` (
	  ID INT NOT NULL AUTO_INCREMENT,
	  CYCLE_NAME CHAR(100) NOT NULL, 
    `DESCRIPTION` VARCHAR(1000),
    USER_ID INT NOT NULL,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 0,
    IS_DELETED TINYINT(1) NOT NULL DEFAULT 0,
    CREATED_DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    UPDATED_DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY(ID),
    KEY(IS_ACTIVE),
    KEY(IS_DELETED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


/* every UPDATE in model, please insert current record here before the update */
CREATE TABLE IF NOT EXISTS `USR_LOOKUP_CYCLES_HISTORY` (
	  ID INT NOT NULL AUTO_INCREMENT,
    CYCLE_ID INT NOT NULL,
	  CYCLE_NAME CHAR(100)NOT NULL, 
    `DESCRIPTION` VARCHAR(1000),
    USER_ID INT NOT NULL,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 0,
    IS_DELETED TINYINT(1) NOT NULL DEFAULT 0,
    CREATED_DATETIME DATETIME NOT NULL, 
    UPDATED_DATETIME DATETIME NOT NULL,
    HISTORY_DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `USR_LOOKUP_USER_CRITERIA_NAME` (
	  ID INT NOT NULL AUTO_INCREMENT,
	  CRITERIA_NAME CHAR(100)NOT NULL, 
    CYCLE_ID INT NOT NULL, 
    USER_ID INT NOT NULL,
    CREATED_DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    UPDATED_DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY(ID),
    KEY(CYCLE_ID),
    KEY(IS_DELETED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS  `USR_LOOKUP_USER_CRITERIA_NAME_HISTORY` (
	  ID INT NOT NULL AUTO_INCREMENT,
    CRITERIA_NAME_ID INT NOT NULL,
	  CRITERIA_NAME CHAR(100) NOT NULL, 
    CYCLE_ID INT NOT NULL, 
    USER_ID INT NOT NULL,
    CREATED_DATETIME DATETIME NOT NULL, 
    UPDATED_DATETIME DATETIME NOT NULL, 
    HISTORY_DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    PRIMARY KEY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS  `USR_LOOKUP_USER_CRITERIA_TERMS` (
	ID INT NOT NULL AUTO_INCREMENT,
    CRITERIA_NAME_ID INT NOT NULL, 
    CRITERIA_TERM CHAR(100) NOT NULL, 
    USER_ID INT NOT NULL, 
    CREATED_DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    UPDATED_DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY(ID),
    KEY(CRITERIA_NAME_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS  `USR_CYCLE_USERS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `GROUP` enum('None','Cycle Admin', 'Weight Criteria Admin') NOT NULL DEFAULT 'NONE',
  `USER_ID` int NOT NULL,
  `CREATED_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  `UPDATED_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
  `IS_DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `UPDATE_USER` int DEFAULT NULL,
  `HISTORY_DATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `user_id_uniq` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS  `USR_CYCLE_USERS_HISTORY` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CYCLE_USER_ID` int NOT NULL,
  `GROUP` VARCHAR(500) NOT NULL DEFAULT 'NONE',
  `USER_ID` int NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `UPDATED_DATETIME` datetime NOT NULL,
  `IS_DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `UPDATE_USER` int DEFAULT NULL,
  `HISTORY_DATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS  `USR_LOOKUP_CRITERIA_WEIGHTS_HISTORY` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `WEIGHT_ID` int NOT NULL,
  `CRITERIA_NAME_ID` int NOT NULL,
  `TITLE` varchar(45) NOT NULL,
  `DESCRIPTION` json DEFAULT NULL,
  `SESSION` json NOT NULL,
  `USER_ID` int NOT NULL,
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `TIMESTAMP` datetime NOT NULL,
  `HISTORY_DATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `USR_OPTION_SCORES_HISTORY` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `SCORE_ID` int NOT NULL,
  `CRITERIA_NAME_ID` int NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(1024) NOT NULL,
  `SESSION` json NOT NULL,
  `PROGRAM_ID` varchar(40) NOT NULL,
  `USER_ID` int NOT NULL,
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `CREATED_TIMESTAMP` datetime NOT NULL,
  `UPDATED_TIMESTAMP` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS  `USR_COA_LINKS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `LINK_TYPE` ENUM('Share', 'Merge') NOT NULL,
  `COA_ID` int NOT NULL,
  `USER_ID` int NOT NULL,
  `IS_DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `CREATED_TIMESTAMP` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS  `USR_DT_SCHEDULER` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CYCLE_ID` int NOT NULL,
  `TYPE` enum('PROGRAM_SCORE_UPLOAD') NOT NULL DEFAULT 'PROGRAM_SCORE_UPLOAD',
  `CRON_STATUS` tinyint(1) NOT NULL DEFAULT '0',
  `CRON_PROCESSED` tinyint(1) NOT NULL DEFAULT '0',
  `ERRORS` VARCHAR(5000) NULL DEFAULT NULL,
  `USER_ID` int NOT NULL,
  `CREATED_TIMESTAMP` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `idx_add_datetime` (`CREATED_TIMESTAMP`),
  KEY `idx_archive_fy` (`CRON_STATUS`,`TYPE`,`CREATED_TIMESTAMP`),
  KEY `idx_cron_status_type` (`CRON_STATUS`, `TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS  `USR_DT_UPLOADS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CYCLE_ID` int NOT NULL,
  `TYPE` enum('PROGRAM_SCORE_UPLOAD') NOT NULL DEFAULT 'PROGRAM_SCORE_UPLOAD',
  `FILE_STATUS` TINYINT(1) NOT NULL,
  `DESCRIPTION` VARCHAR(5000),
  `VERSION` CHAR(20) DEFAULT NULL, 
  `S3_PATH` VARCHAR(1500)DEFAULT NULL,
  `FILE_NAME` VARCHAR(500)DEFAULT NULL,
  `USER_ID` int NOT NULL,
  `UPDATE_USER_ID` int NOT NULL,
  `IS_DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `CREATED_TIMESTAMP` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_TIMESTAMP` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `idx_add_datetime` (`CREATED_TIMESTAMP`),
  KEY `idx_archive_fy` (`TYPE`,`CREATED_TIMESTAMP`),
  KEY `idx_type_file_status` (`FILE_STATUS`, `TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS  `USR_DT_SCHEDULER_MAP` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `TYPE` enum('PROGRAM_SCORE_UPLOAD') NOT NULL DEFAULT 'PROGRAM_SCORE_UPLOAD',
  `DT_SCHEDULER_ID` int NOT NULL,
  `MAP_ID` int NOT NULL,
  `CREATED_TIMESTAMP` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `idx_add_datetime` (`CREATED_TIMESTAMP`),
  KEY `idx_archive_fy` (`TYPE`,`CREATED_TIMESTAMP`),
  KEY `idx_type_cron_status_fiscal_year` (`TYPE`),
  KEY `idx_dt_scheduler_id` (`DT_SCHEDULER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE `USR_DT_UPLOADS` 
ADD COLUMN `TITLE` VARCHAR(100) NOT NULL AFTER `FILE_STATUS`,
CHANGE COLUMN `DESCRIPTION` `DESCRIPTION` VARCHAR(5000) NOT NULL ,
CHANGE COLUMN `VERSION` `VERSION` CHAR(20) NOT NULL ,
CHANGE COLUMN `S3_PATH` `S3_PATH` VARCHAR(1500) NOT NULL ,
CHANGE COLUMN `FILE_NAME` `FILE_NAME` VARCHAR(500) NOT NULL ;

ALTER TABLE `USR_LOOKUP_CRITERIA_WEIGHTS` 
ADD INDEX `idx_user_id_criteria_name_id` (`USER_ID` ASC, `CRITERIA_NAME_ID` ASC) VISIBLE;
;
ALTER TABLE `USR_OPTION_SCORES_HISTORY` 
ADD COLUMN `HISTORY_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `UPDATED_TIMESTAMP`,
CHANGE COLUMN `UPDATED_TIMESTAMP` `UPDATED_TIMESTAMP` DATETIME NOT NULL ;

ALTER TABLE `USR_LOOKUP_USER_CRITERIA_TERMS` 
ADD UNIQUE INDEX `CRITERIA_TERM` (`CRITERIA_NAME_ID` ASC, `CRITERIA_TERM` ASC) VISIBLE;
;

ALTER TABLE `USR_ISSUE_AD_SAVES` 
DROP INDEX `idx_program_id_eoc_code` ,
ADD INDEX `idx_program_id_eoc_code` (`EVENT_ID` ASC) VISIBLE;
;

ALTER TABLE `USR_ISSUE_AO_SAVES` 
DROP INDEX `idx_program_id_eoc_code` ,
ADD INDEX `idx_program_id_eoc_code` (`EVENT_ID` ASC) VISIBLE;
;

ALTER TABLE `USR_ZBT_AD_SAVES` 
DROP INDEX `idx_program_id_eoc_code` ,
ADD INDEX `idx_program_id_eoc_code` (`EVENT_ID` ASC) VISIBLE;
;

ALTER TABLE `USR_ZBT_AO_SAVES` 
DROP INDEX `idx_program_id_eoc_code` ,
ADD INDEX `idx_program_id_eoc_code` (`EVENT_ID` ASC) VISIBLE;
;

TRUNCATE USR_LOOKUP_CYCLES;
TRUNCATE USR_LOOKUP_USER_CRITERIA_NAME;
TRUNCATE USR_LOOKUP_USER_CRITERIA_NAME_HISTORY;
TRUNCATE USR_LOOKUP_USER_CRITERIA_TERMS;

INSERT INTO USR_LOOKUP_CYCLES (CYCLE_NAME, `DESCRIPTION`, IS_ACTIVE) VALUES('FY26_ISS_1', 'Initial Cycle', 1);
INSERT INTO USR_LOOKUP_USER_CRITERIA_NAME (CRITERIA_NAME, CYCLE_ID) VALUES('Initial Criteria', 1);

INSERT INTO USR_LOOKUP_USER_CRITERIA_TERMS (CRITERIA_NAME_ID, CRITERIA_TERM) 
VALUES(1, 'RISK'),
(1, 'READINESS'),
(1, 'FOUNDATIONAL'),
(1, 'DESIGN_ALIGNMENT'),
(1, 'COST_PRACTICALITY'),
(1, 'STRATEGIC_ALIGNMENT'),
(1, 'MANPOWER_FEASIBILITY'),
(1, 'POLITICAL_FEASIBILITY'),
(1, 'ACQUISITION_FEASIBILITY'),
(1, 'COST_PROFILE_FEASIBILITY'),
(1, 'SECURITY_COOPERATION_FEASIBILITY');

UPDATE USR_LOOKUP_CRITERIA_WEIGHTS SET CRITERIA_NAME_ID = 1 WHERE CRITERIA_NAME_ID IS NULL;
UPDATE USR_OPTION_SCORES SET CRITERIA_NAME_ID = 1 WHERE CRITERIA_NAME_ID IS NULL;
UPDATE USR_LOOKUP_SAVED_COA SET CRITERIA_NAME_ID = 1 WHERE CRITERIA_NAME_ID IS NULL;
UPDATE USR_LOOKUP_USER_SAVED_COA SET CRITERIA_NAME_ID = 1 WHERE CRITERIA_NAME_ID IS NULL;

CREATE TABLE IF NOT EXISTS  USR_LOOKUP_USER_SHARED_COA (
	ID INT NOT NULL AUTO_INCREMENT,
    ORIGINAL_COA_ID INT NOT NULL,
    NEW_COA_ID INT NOT NULL,
    ORIGINAL_USER_ID INT NOT NULL,
    NEW_USER_ID INT NOT NULL,
    IS_REVOKED TINYINT NOT NULL DEFAULT 0,
    CREATED_DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(ID),
    KEY(ORIGINAL_COA_ID),
    KEY(ORIGINAL_COA_ID, IS_REVOKED),
    KEY(NEW_COA_ID),
    KEY(NEW_COA_ID, IS_REVOKED),
    KEY(NEW_COA_ID, NEW_USER_ID, IS_REVOKED)
);

 