ALTER TABLE `USR_ISSUE_AD_SAVES` 
ADD COLUMN `EVENT_ID` VARCHAR(100) NULL DEFAULT NULL AFTER `EOC_CODE`,
DROP INDEX `idx_program_id_eoc_code` ,
ADD INDEX `idx_program_id_eoc_code` (`PROGRAM_ID` ASC, `EOC_CODE` ASC, `EVENT_ID` ASC) VISIBLE;
;

ALTER TABLE `USR_ISSUE_AO_SAVES` 
ADD COLUMN `EVENT_ID` VARCHAR(100) NULL DEFAULT NULL AFTER `EOC_CODE`,
DROP INDEX `idx_program_id_eoc_code` ,
ADD INDEX `idx_program_id_eoc_code` (`PROGRAM_ID` ASC, `EOC_CODE` ASC, `EVENT_ID` ASC) VISIBLE;
;

ALTER TABLE `USR_ZBT_AO_SAVES` 
ADD COLUMN `EVENT_ID` VARCHAR(100) NULL DEFAULT NULL AFTER `EOC_CODE`,
DROP INDEX `idx_program_id_eoc_code` ,
ADD INDEX `idx_program_id_eoc_code` (`PROGRAM_ID` ASC, `EOC_CODE` ASC, `EVENT_ID` ASC) VISIBLE;
;

ALTER TABLE `USR_ZBT_AD_SAVES` 
ADD COLUMN `EVENT_ID` VARCHAR(100) NULL DEFAULT NULL AFTER `EOC_CODE`,
DROP INDEX `idx_program_id_eoc_code` ,
ADD INDEX `idx_program_id_eoc_code` (`PROGRAM_ID` ASC, `EOC_CODE` ASC, `EVENT_ID` ASC) VISIBLE;
;

TRUNCATE USR_ISSUE_AD_SAVES;
TRUNCATE USR_ISSUE_AO_SAVES;
TRUNCATE USR_ZBT_AO_SAVES;
TRUNCATE USR_ZBT_AD_SAVES;


ALTER TABLE `USR_ISSUE_AO_SAVES_HISTORY` 
ADD COLUMN `EVENT_ID` VARCHAR(100) NOT NULL AFTER `EOC_CODE`;

ALTER TABLE `USR_ISSUE_AD_SAVES_HISTORY` 
ADD COLUMN `EVENT_ID` VARCHAR(100) NOT NULL AFTER `EOC_CODE`;


ALTER TABLE `USR_ZBT_AO_SAVES_HISTORY` 
ADD COLUMN `EVENT_ID` VARCHAR(100) NOT NULL AFTER `EOC_CODE`;

ALTER TABLE `USR_ZBT_AD_SAVES_HISTORY` 
ADD COLUMN `EVENT_ID` VARCHAR(100) NOT NULL AFTER `EOC_CODE`;

TRUNCATE USR_ISSUE_AD_SAVES_HISTORY;
TRUNCATE USR_ISSUE_AO_SAVES_HISTORY;
TRUNCATE USR_ZBT_AO_SAVES_HISTORY;
TRUNCATE USR_ZBT_AD_SAVES_HISTORY;
