CREATE TABLE `USR_ADMIN_USERS_HISTORY` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ADMIN_ID` int NOT NULL,
  `GROUP` enum('NONE','AO and AD Admin') NOT NULL DEFAULT 'NONE',
  `USER_ID` int NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `UPDATED_DATETIME` datetime NOT NULL,
  `IS_DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `UPDATE_USER` int DEFAULT NULL,
  `HISTORY_DATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `USR_AO_AD_USERS_HISTORY` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `AO_AD_ID` int NOT NULL,
  `GROUP` enum('None','AO','AD','AO and AD') NOT NULL DEFAULT 'NONE',
  `USER_ID` int NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `UPDATED_DATETIME` datetime NOT NULL,
  `IS_DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `UPDATE_USER` int DEFAULT NULL,
  `HISTORY_DATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `USR_ISSUE_AO_SAVES` (
  `ID` int NOT NULL DEFAULT '0',
  `AO_RECOMENDATION` ENUM('Approve at scale', 'Disapprove') DEFAULT NULL,
  `AO_COMMENT` varchar(2000) DEFAULT NULL,
  `AO_USER_ID` int DEFAULT NULL,
  `CREATED_DATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `PROGRAM_ID` varchar(100) NOT NULL,
  `EOC_CODE` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
 
CREATE TABLE `USR_ZBT_AO_SAVES` (
  `ID` int NOT NULL DEFAULT '0',
  `AO_RECOMENDATION` ENUM('Approve at scale', 'Disapprove') DEFAULT NULL,
  `AO_COMMENT` varchar(2000) DEFAULT NULL,
  `AO_USER_ID` int DEFAULT NULL,
  `CREATED_DATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `PROGRAM_ID` varchar(100) NOT NULL,
  `EOC_CODE` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `USR_ISSUE_AD_SAVES` (
  `ID` int NOT NULL DEFAULT '0',
  `AD_RECOMENDATION` ENUM('Approve at scale', 'Disapprove') DEFAULT NULL,
  `AD_COMMENT` varchar(2000) DEFAULT NULL,
  `AD_USER_ID` int DEFAULT NULL,
  `CREATED_DATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `PROGRAM_ID` varchar(100) NOT NULL,
  `EOC_CODE` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
 
CREATE TABLE `USR_ZBT_AD_SAVES` (
  `ID` int NOT NULL DEFAULT '0',
  `AD_RECOMENDATION` ENUM('Approve at scale', 'Disapprove') DEFAULT NULL,
  `AD_COMMENT` varchar(2000) DEFAULT NULL,
  `AD_USER_ID` int DEFAULT NULL,
  `CREATED_DATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `PROGRAM_ID` varchar(100) NOT NULL,
  `EOC_CODE` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE USR_ISSUE_AOAD_SAVES;
DROP TABLE USR_ZBT_AOAD_SAVES;

CREATE TABLE `USR_ISSUE_AD_SAVES_HISTORY` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ISSUE_AD_ID` int NOT NULL,
  `AD_RECOMENDATION`  enum('Approve','Approve at scale','Disapprove') DEFAULT NULL,
  `AD_COMMENT` varchar(2000) DEFAULT NULL,
  `AD_USER_ID` int DEFAULT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `UPDATED_DATETIME` datetime NOT NULL,
  `PROGRAM_ID` varchar(100) NOT NULL,
  `EOC_CODE` varchar(100) DEFAULT NULL,
  `HISTORY_DATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `USR_ISSUE_AO_SAVES_HISTORY` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ISSUE_AO_ID` int NOT NULL,
  `AO_RECOMENDATION` enum('Approve','Approve at scale','Disapprove') DEFAULT NULL,
  `AO_COMMENT` varchar(2000) DEFAULT NULL,
  `AO_USER_ID` int DEFAULT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `UPDATED_DATETIME` datetime NOT NULL,
  `PROGRAM_ID` varchar(100) NOT NULL,
  `EOC_CODE` varchar(100) DEFAULT NULL,
  `HISTORY_DATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `USR_ZBT_AD_SAVES_HISTORY` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ZBT_AD_ID` int NOT NULL,
  `AD_RECOMENDATION` enum('Approve as requested','Disapprove') DEFAULT NULL,
  `AD_COMMENT` varchar(2000) DEFAULT NULL,
  `AD_USER_ID` int DEFAULT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `UPDATED_DATETIME` datetime NOT NULL,
  `PROGRAM_ID` varchar(100) NOT NULL,
  `EOC_CODE` varchar(100) DEFAULT NULL,
  `HISTORY_DATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `USR_ZBT_AO_SAVES_HISTORY` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ZBT_AO_ID` int NOT NULL,
  `AO_RECOMENDATION` enum('Approve as requested','Disapprove') DEFAULT NULL,
  `AO_COMMENT` varchar(2000) DEFAULT NULL,
  `AO_USER_ID` int DEFAULT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `UPDATED_DATETIME` datetime NOT NULL,
  `PROGRAM_ID` varchar(100) NOT NULL,
  `EOC_CODE` varchar(100) NOT NULL,
  `HISTORY_DATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE `USR_ZBT_AD_SAVES` 
ADD INDEX `idx_program_id_eoc_code` (`PROGRAM_ID` ASC, `EOC_CODE` ASC) VISIBLE;

ALTER TABLE `USR_ZBT_AO_SAVES` 
ADD INDEX `idx_program_id_eoc_code` (`PROGRAM_ID` ASC, `EOC_CODE` ASC) VISIBLE;

ALTER TABLE `USR_ISSUE_AD_SAVES` 
ADD INDEX `idx_program_id_eoc_code` (`PROGRAM_ID` ASC, `EOC_CODE` ASC) VISIBLE;

ALTER TABLE `USR_ISSUE_AO_SAVES` 
ADD INDEX `idx_program_id_eoc_code` (`PROGRAM_ID` ASC, `EOC_CODE` ASC) VISIBLE;

ALTER TABLE `USR_LOOKUP_SAVED_COA` 
ADD COLUMN `OVERRIDE_TABLE_SESSION` JSON DEFAULT NULL,
ADD COLUMN `OVERRIDE_TABLE_METADATA` JSON DEFAULT NULL,
ADD COLUMN `OVERRIDE_FORM_SESSION` JSON DEFAULT NULL;

ALTER TABLE `USR_LOOKUP_USER_SAVED_COA`
ADD COLUMN `STATE` TEXT DEFAULT NULL;