
SET @dbname = DATABASE();
SET @tablename = 'USR_DT_LOOKUP_METADATA';
SET @newcol = 'POM_POSITION';
SELECT count(*) INTO @updated FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @dbname and TABLE_NAME=@tablename and COLUMN_NAME=@newcol;
SET @sql := IF(@updated = 0,'SELECT "Table already updated";',CONCAT('ALTER TABLE ', @dbname, '.', @tablename, ' ', " DROP COLUMN POM_POSITION;"));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @dbname = DATABASE();
SET @tablename = 'USR_DT_LOOKUP_METADATA';
SET @newcol = 'TABLE_TYPE_DESCR';
SELECT count(*) INTO @updated FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @dbname and TABLE_NAME=@tablename and COLUMN_NAME=@newcol;
SET @sql := IF(@updated = 1,'SELECT "Table already updated";',CONCAT('ALTER TABLE ', @dbname, '.', @tablename, ' ', " ADD COLUMN `TABLE_TYPE_DESCR` varchar(30) NOT NULL AFTER POM_YEAR;"));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @dbname = DATABASE();
SET @tablename = 'USR_DT_UPLOADS';
SET @newcol = 'TYPE';
SET @newtype = "ENUM('PROGRAM_SCORE_UPLOAD','DT_UPLOAD_BASE_UPLOAD','DT_UPLOAD_BASE_UPLOAD_APPEND','DT_UPLOAD_EXTRACT_UPLOAD')";
SELECT count(*) INTO @updated FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @dbname and TABLE_NAME=@tablename and COLUMN_NAME=@newcol  AND COLUMN_TYPE=@newtype;
SET @sql := IF(@updated = 1,'SELECT "Table already updated";',CONCAT('ALTER TABLE ', @dbname, '.', @tablename, ' ', " CHANGE TYPE TYPE ENUM('PROGRAM_SCORE_UPLOAD','DT_UPLOAD_BASE_UPLOAD','DT_UPLOAD_BASE_UPLOAD_APPEND','DT_UPLOAD_EXTRACT_UPLOAD') DEFAULT 'PROGRAM_SCORE_UPLOAD';"));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @dbname = DATABASE();
SET @tablename = 'USR_DT_LOOKUP_METADATA';
SET @newcol = 'CAP_SPONSOR';
SELECT count(*) INTO @updated FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @dbname and TABLE_NAME=@tablename and COLUMN_NAME=@newcol;
SET @sql := IF(@updated = 1,'SELECT "Table already updated";',CONCAT('ALTER TABLE ', @dbname, '.', @tablename, ' ', " ADD COLUMN `CAP_SPONSOR` VARCHAR(13) NOT NULL AFTER `IS_ACTIVE`;"));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;


SET @dbname = DATABASE();
SET @tablename = 'USR_DT_GIT_DATA';
SET @newcol = 'TYPE';
SET @newtype = "ENUM('UPLOAD_FILE','PROCESS_FILE','CANCEL_FILE','DELETE_FILE','CREATE_METADATA','CREATE_DATABASE','USER_DATA_OPEN','USER_DATA_CLOSE','USER_DATA_EDIT_HISTORY','USER_DATA_SAVE_START','USER_DATA_SAVE_END','USER_DATA_CANCEL','USER_DATA_FINAL_SUBMISSION','ADMIN_APPROVAL')";
SELECT count(*) INTO @updated FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @dbname and TABLE_NAME=@tablename and COLUMN_NAME=@newcol  AND COLUMN_TYPE=@newtype;
SET @sql := IF(@updated = 1,'SELECT "Table already updated";',CONCAT('ALTER TABLE ', @dbname, '.', @tablename, ' ', " CHANGE COLUMN `TYPE` `TYPE` ENUM('UPLOAD_FILE', 'PROCESS_FILE', 'CANCEL_FILE', 'DELETE_FILE', 'CREATE_METADATA', 'CREATE_DATABASE', 'USER_DATA_OPEN', 'USER_DATA_CLOSE', 'USER_DATA_EDIT_HISTORY', 'USER_DATA_SAVE_START', 'USER_DATA_SAVE_END', 'USER_DATA_CANCEL', 'USER_DATA_FINAL_SUBMISSION', 'ADMIN_APPROVAL') NOT NULL ;"));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @dbname = DATABASE();
SET @tablename = 'USR_DT_GIT_MAP';
SET @newcol = 'TYPE';
SET @newtype = "ENUM('UPLOAD_FILE','PROCESS_FILE','CANCEL_FILE','DELETE_FILE','CREATE_METADATA','CREATE_DATABASE','USER_DATA_OPEN','USER_DATA_CLOSE','USER_DATA_EDIT_HISTORY','USER_DATA_SAVE_START','USER_DATA_SAVE_END','USER_DATA_CANCEL','USER_DATA_FINAL_SUBMISSION','ADMIN_APPROVAL')";
SELECT count(*) INTO @updated FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @dbname and TABLE_NAME=@tablename and COLUMN_NAME=@newcol  AND COLUMN_TYPE=@newtype;
SET @sql := IF(@updated = 1,'SELECT "Table already updated";',CONCAT('ALTER TABLE ', @dbname, '.', @tablename, ' ', " CHANGE COLUMN `TYPE` `TYPE` ENUM('UPLOAD_FILE', 'PROCESS_FILE', 'CANCEL_FILE', 'DELETE_FILE', 'CREATE_METADATA', 'CREATE_DATABASE', 'USER_DATA_OPEN', 'USER_DATA_CLOSE', 'USER_DATA_EDIT_HISTORY', 'USER_DATA_SAVE_START', 'USER_DATA_SAVE_END', 'USER_DATA_CANCEL', 'USER_DATA_FINAL_SUBMISSION', 'ADMIN_APPROVAL') NOT NULL ;"));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @dbname = DATABASE();
SET @tablename = 'USR_DT_LOOKUP_METADATA';
SET @index_name = "CAP_SPONSOR";
SELECT count(*) INTO @updated FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME=@tablename AND INDEX_NAME=@index_name;
SET @sql := IF(@updated > 0,  CONCAT('DROP INDEX ', @index_name ,' ON ', @tablename ), ' SELECT "index not found"'); 
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SELECT count(*) INTO @updated FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME=@tablename AND INDEX_NAME=@index_name;
SET @sql := IF(@updated != 0,'SELECT "INDEX NOT CREATED";', CONCAT('CREATE INDEX ', @index_name, ' ON ', @tablename,  ' (`CAP_SPONSOR` ASC);'));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

