
ALTER TABLE `USR_LOOKUP_USER_CRITERIA_NAME_HISTORY` 
ADD COLUMN `HISTORY_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `UPDATED_DATETIME`,
CHANGE COLUMN `CREATED_DATETIME` `CREATED_DATETIME` DATETIME NOT NULL ,
CHANGE COLUMN `UPDATED_DATETIME` `UPDATED_DATETIME` DATETIME NOT NULL ;

ALTER TABLE `USR_LOOKUP_SAVED_COA` 
CHANGE COLUMN `CREATED_DATETIME` `CREATED_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;
