ALTER TABLE `USR_LOOKUP_POM_POSITION_CYCLE` 
CHANGE COLUMN `POM_YEAR` `POM_ID` INT NOT NULL ;

TRUNCATE USR_LOOKUP_POM_POSITION_CYCLE;

INSERT INTO USR_LOOKUP_POM_POSITION_CYCLE (POM_ID, CYCLE_ID, USER_ID) VALUES(1,1,1);

CREATE TABLE USR_LOOKUP_POM_POSITION_HISTORY(
	ID INT NOT NULL AUTO_INCREMENT,
    POM_ID INT NOT NULL,
    POM_YEAR VARCHAR(45) NOT NULL,
    LATEST_POSITION varchar(30) NOT NULL,
    IS_ACTIVE tinyint(1) NOT NULL DEFAULT 1,
    USER_ID INT NOT NULL,
    CREATED_DATETIME TIMESTAMP NOT NULL,
    UPDATED_TIMESTAMP datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE `USR_LOOKUP_POM_POSITION` 
ADD UNIQUE INDEX `idx_uniq_POM_YEAR` (`POM_YEAR` ASC) VISIBLE;
