-- Add missing DT_ tables that are required by the SOCOM application
-- These tables are defined in the backup files but missing from the current database

USE SOCOM_UI;

-- Create missing DT_BUDGET_EXECUTION table
CREATE TABLE IF NOT EXISTS DT_BUDGET_EXECUTION (
  `id` int NOT NULL AUTO_INCREMENT,
  `FISCAL_YEAR` int NOT NULL,
  `PROGRAM_CODE` varchar(100) NOT NULL,
  `PROGRAM_NAME` varchar(255) NOT NULL,
  `BUDGET_AMOUNT` decimal(15,2) DEFAULT '0.00',
  `EXECUTED_AMOUNT` decimal(15,2) DEFAULT '0.00',
  `VARIANCE_AMOUNT` decimal(15,2) DEFAULT '0.00',
  `EXECUTION_RATE` decimal(5,2) DEFAULT '0.00',
  `QUARTER` int DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `FISCAL_YEAR` (`FISCAL_YEAR`),
  KEY `PROGRAM_CODE` (`PROGRAM_CODE`),
  KEY `QUARTER` (`QUARTER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create missing DT_ISS_EXTRACT_2024 table
CREATE TABLE IF NOT EXISTS DT_ISS_EXTRACT_2024 (
  `id` int NOT NULL AUTO_INCREMENT,
  `CAPABILITY_SPONSOR_CODE` varchar(255) NOT NULL,
  `EVENT_NAME` varchar(500) NOT NULL,
  `DELTA_AMT` decimal(15,2) DEFAULT '0.00',
  `FISCAL_YEAR` int DEFAULT '2024',
  `PROGRAM_NAME` varchar(500) DEFAULT NULL,
  `RESOURCE_CATEGORY_CODE` varchar(100) DEFAULT NULL,
  `EXECUTION_MANAGER_CODE` varchar(100) DEFAULT NULL,
  `PROGRAM_CODE` varchar(100) DEFAULT NULL,
  `EOC_CODE` varchar(100) DEFAULT NULL,
  `OSD_PE_CODE` varchar(100) DEFAULT NULL,
  `APPROVAL_STATUS` varchar(50) DEFAULT 'PENDING',
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_capability_sponsor` (`CAPABILITY_SPONSOR_CODE`),
  KEY `idx_event_name` (`EVENT_NAME`),
  KEY `idx_fiscal_year` (`FISCAL_YEAR`),
  KEY `idx_program_name` (`PROGRAM_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create missing DT_ISS_EXTRACT_2025 table
CREATE TABLE IF NOT EXISTS DT_ISS_EXTRACT_2025 (
  `id` int NOT NULL AUTO_INCREMENT,
  `CAPABILITY_SPONSOR_CODE` varchar(255) NOT NULL,
  `EVENT_NAME` varchar(500) NOT NULL,
  `DELTA_AMT` decimal(15,2) DEFAULT '0.00',
  `FISCAL_YEAR` int DEFAULT '2025',
  `PROGRAM_NAME` varchar(500) DEFAULT NULL,
  `RESOURCE_CATEGORY_CODE` varchar(100) DEFAULT NULL,
  `EXECUTION_MANAGER_CODE` varchar(100) DEFAULT NULL,
  `PROGRAM_CODE` varchar(100) DEFAULT NULL,
  `EOC_CODE` varchar(100) DEFAULT NULL,
  `OSD_PE_CODE` varchar(100) DEFAULT NULL,
  `APPROVAL_STATUS` varchar(50) DEFAULT 'PENDING',
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_capability_sponsor` (`CAPABILITY_SPONSOR_CODE`),
  KEY `idx_event_name` (`EVENT_NAME`),
  KEY `idx_fiscal_year` (`FISCAL_YEAR`),
  KEY `idx_program_name` (`PROGRAM_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create missing DT_PB_COMPARISON table
CREATE TABLE IF NOT EXISTS DT_PB_COMPARISON (
  `id` int NOT NULL AUTO_INCREMENT,
  `FISCAL_YEAR` int NOT NULL,
  `PROGRAM_CODE` varchar(100) NOT NULL,
  `PROGRAM_NAME` varchar(255) NOT NULL,
  `PB_AMOUNT` decimal(15,2) DEFAULT '0.00',
  `ACTUAL_AMOUNT` decimal(15,2) DEFAULT '0.00',
  `VARIANCE_AMOUNT` decimal(15,2) DEFAULT '0.00',
  `VARIANCE_PERCENTAGE` decimal(5,2) DEFAULT '0.00',
  `QUARTER` int DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `FISCAL_YEAR` (`FISCAL_YEAR`),
  KEY `PROGRAM_CODE` (`PROGRAM_CODE`),
  KEY `QUARTER` (`QUARTER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create missing DT_ZBT_EXTRACT_2024 table
CREATE TABLE IF NOT EXISTS DT_ZBT_EXTRACT_2024 (
  `id` int NOT NULL AUTO_INCREMENT,
  `CAPABILITY_SPONSOR_CODE` varchar(255) NOT NULL,
  `EVENT_NAME` varchar(500) NOT NULL,
  `DELTA_AMT` decimal(15,2) DEFAULT '0.00',
  `FISCAL_YEAR` int DEFAULT '2024',
  `PROGRAM_NAME` varchar(500) DEFAULT NULL,
  `RESOURCE_CATEGORY_CODE` varchar(100) DEFAULT NULL,
  `EXECUTION_MANAGER_CODE` varchar(100) DEFAULT NULL,
  `PROGRAM_CODE` varchar(100) DEFAULT NULL,
  `EOC_CODE` varchar(100) DEFAULT NULL,
  `OSD_PE_CODE` varchar(100) DEFAULT NULL,
  `APPROVAL_STATUS` varchar(50) DEFAULT 'PENDING',
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_capability_sponsor` (`CAPABILITY_SPONSOR_CODE`),
  KEY `idx_event_name` (`EVENT_NAME`),
  KEY `idx_fiscal_year` (`FISCAL_YEAR`),
  KEY `idx_program_name` (`PROGRAM_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create missing DT_ZBT_EXTRACT_2025 table
CREATE TABLE IF NOT EXISTS DT_ZBT_EXTRACT_2025 (
  `id` int NOT NULL AUTO_INCREMENT,
  `CAPABILITY_SPONSOR_CODE` varchar(255) NOT NULL,
  `EVENT_NAME` varchar(500) NOT NULL,
  `DELTA_AMT` decimal(15,2) DEFAULT '0.00',
  `FISCAL_YEAR` int DEFAULT '2025',
  `PROGRAM_NAME` varchar(500) DEFAULT NULL,
  `RESOURCE_CATEGORY_CODE` varchar(100) DEFAULT NULL,
  `EXECUTION_MANAGER_CODE` varchar(100) DEFAULT NULL,
  `PROGRAM_CODE` varchar(100) DEFAULT NULL,
  `EOC_CODE` varchar(100) DEFAULT NULL,
  `OSD_PE_CODE` varchar(100) DEFAULT NULL,
  `APPROVAL_STATUS` varchar(50) DEFAULT 'PENDING',
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_capability_sponsor` (`CAPABILITY_SPONSOR_CODE`),
  KEY `idx_event_name` (`EVENT_NAME`),
  KEY `idx_fiscal_year` (`FISCAL_YEAR`),
  KEY `idx_program_name` (`PROGRAM_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Verify the tables were created
SELECT 'DT_BUDGET_EXECUTION' as table_name, COUNT(*) as record_count FROM DT_BUDGET_EXECUTION
UNION ALL
SELECT 'DT_ISS_EXTRACT_2024' as table_name, COUNT(*) as record_count FROM DT_ISS_EXTRACT_2024
UNION ALL
SELECT 'DT_ISS_EXTRACT_2025' as table_name, COUNT(*) as record_count FROM DT_ISS_EXTRACT_2025
UNION ALL
SELECT 'DT_PB_COMPARISON' as table_name, COUNT(*) as record_count FROM DT_PB_COMPARISON
UNION ALL
SELECT 'DT_ZBT_EXTRACT_2024' as table_name, COUNT(*) as record_count FROM DT_ZBT_EXTRACT_2024
UNION ALL
SELECT 'DT_ZBT_EXTRACT_2025' as table_name, COUNT(*) as record_count FROM DT_ZBT_EXTRACT_2025;



