-- Add missing USR tables that are required by the SOCOM application
-- These tables are defined in the backup files but missing from the current database

USE SOCOM_UI;

-- Create missing USR_CAP_USERS_HISTORY table
CREATE TABLE IF NOT EXISTS USR_CAP_USERS_HISTORY (
  `HISTORY_ID` int NOT NULL AUTO_INCREMENT,
  `USER_ID` int NOT NULL,
  `CAPABILITY_SPONSOR_CODE` varchar(10) NOT NULL,
  `ACTION_TYPE` enum('CREATED','UPDATED','DELETED','ACTIVATED','DEACTIVATED') NOT NULL,
  `OLD_VALUES` text,
  `NEW_VALUES` text,
  `IS_ACTIVE` tinyint(1) DEFAULT '1',
  `CREATED_DATETIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`HISTORY_ID`),
  KEY `USER_ID` (`USER_ID`),
  KEY `CAPABILITY_SPONSOR_CODE` (`CAPABILITY_SPONSOR_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create missing USR_SITE_USERS_HISTORY table
CREATE TABLE IF NOT EXISTS USR_SITE_USERS_HISTORY (
  `HISTORY_ID` int NOT NULL AUTO_INCREMENT,
  `USER_ID` int NOT NULL,
  `USER_NAME` varchar(100) NOT NULL,
  `USER_EMAIL` varchar(255) NOT NULL,
  `USER_ROLE` varchar(50) NOT NULL,
  `ACTION_TYPE` enum('CREATED','UPDATED','DELETED','ACTIVATED','DEACTIVATED') NOT NULL,
  `OLD_VALUES` text,
  `NEW_VALUES` text,
  `IS_ACTIVE` tinyint(1) DEFAULT '1',
  `CREATED_DATETIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`HISTORY_ID`),
  KEY `USER_ID` (`USER_ID`),
  KEY `USER_ROLE` (`USER_ROLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create missing USR_ZBT_AD_FINAL_SAVES table
CREATE TABLE IF NOT EXISTS USR_ZBT_AD_FINAL_SAVES (
  `SAVE_ID` int NOT NULL AUTO_INCREMENT,
  `USER_ID` int NOT NULL,
  `ZBT_DATA` longtext NOT NULL,
  `SAVE_NAME` varchar(255) NOT NULL,
  `SAVE_DESCRIPTION` text,
  `FISCAL_YEAR` int DEFAULT NULL,
  `CYCLE_ID` int DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) DEFAULT '1',
  `CREATED_DATETIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATETIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`SAVE_ID`),
  KEY `USER_ID` (`USER_ID`),
  KEY `FISCAL_YEAR` (`FISCAL_YEAR`),
  KEY `CYCLE_ID` (`CYCLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create missing USR_LOOKUP_CRITERIA_WEIGHTS table
CREATE TABLE IF NOT EXISTS USR_LOOKUP_CRITERIA_WEIGHTS (
  `WEIGHT_ID` int NOT NULL AUTO_INCREMENT,
  `CRITERIA_NAME_ID` int NOT NULL,
  `WEIGHT_NAME` varchar(100) NOT NULL,
  `WEIGHT_VALUE` decimal(5,2) NOT NULL,
  `WEIGHT_DESCRIPTION` text,
  `IS_ACTIVE` tinyint(1) DEFAULT '1',
  `CREATED_DATETIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`WEIGHT_ID`),
  KEY `CRITERIA_NAME_ID` (`CRITERIA_NAME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create missing USR_LOOKUP_CYCLES table
CREATE TABLE IF NOT EXISTS USR_LOOKUP_CYCLES (
  `CYCLE_ID` int NOT NULL AUTO_INCREMENT,
  `CYCLE_NAME` varchar(255) NOT NULL,
  `CYCLE_YEAR` int NOT NULL,
  `CYCLE_TYPE` enum('POM','ZBT','ISS','COA') NOT NULL,
  `CYCLE_STATUS` enum('DRAFT','ACTIVE','COMPLETED','ARCHIVED') DEFAULT 'DRAFT',
  `START_DATE` date DEFAULT NULL,
  `END_DATE` date DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) DEFAULT '1',
  `CREATED_DATETIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATETIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CYCLE_ID`),
  UNIQUE KEY `CYCLE_NAME_YEAR` (`CYCLE_NAME`,`CYCLE_YEAR`),
  KEY `CYCLE_TYPE` (`CYCLE_TYPE`),
  KEY `CYCLE_STATUS` (`CYCLE_STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Verify the tables were created
SELECT 'USR_CAP_USERS_HISTORY' as table_name, COUNT(*) as record_count FROM USR_CAP_USERS_HISTORY
UNION ALL
SELECT 'USR_SITE_USERS_HISTORY' as table_name, COUNT(*) as record_count FROM USR_SITE_USERS_HISTORY
UNION ALL
SELECT 'USR_ZBT_AD_FINAL_SAVES' as table_name, COUNT(*) as record_count FROM USR_ZBT_AD_FINAL_SAVES
UNION ALL
SELECT 'USR_LOOKUP_CRITERIA_WEIGHTS' as table_name, COUNT(*) as record_count FROM USR_LOOKUP_CRITERIA_WEIGHTS
UNION ALL
SELECT 'USR_LOOKUP_CYCLES' as table_name, COUNT(*) as record_count FROM USR_LOOKUP_CYCLES;


