-- SOCOM Database Health Check SQL Script
-- Run this script to document the current state of the database

-- Database connection test
SELECT VERSION() as 'MySQL Version';

-- Show all tables in SOCOM_UI
SHOW TABLES FROM SOCOM_UI;

-- Check tables with PROGRAM_GROUP column (this is the problematic column)
SELECT 
    TABLE_NAME, 
    COLUMN_NAME, 
    DATA_TYPE, 
    IS_NULLABLE, 
    COLUMN_DEFAULT,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE COLUMN_NAME LIKE '%PROGRAM_GROUP%' 
AND TABLE_SCHEMA = 'SOCOM_UI'
ORDER BY TABLE_NAME;

-- Check all columns in RESOURCE_CONSTRAINED_COA_2024 table
DESCRIBE SOCOM_UI.RESOURCE_CONSTRAINED_COA_2024;

-- Check all columns in ISS_SUMMARY tables
DESCRIBE SOCOM_UI.ISS_SUMMARY_2024;
DESCRIBE SOCOM_UI.ISS_SUMMARY_2025;

-- Check lookup table structures
DESCRIBE SOCOM_UI.LOOKUP_PROGRAM;
DESCRIBE SOCOM_UI.LOOKUP_SPONSOR;
DESCRIBE SOCOM_UI.LOOKUP_RESOURCE_CATEGORY;

-- Count rows in key tables
SELECT 'LOOKUP_PROGRAM' as table_name, COUNT(*) as row_count FROM SOCOM_UI.LOOKUP_PROGRAM
UNION ALL
SELECT 'LOOKUP_SPONSOR' as table_name, COUNT(*) as row_count FROM SOCOM_UI.LOOKUP_SPONSOR
UNION ALL
SELECT 'LOOKUP_RESOURCE_CATEGORY' as table_name, COUNT(*) as row_count FROM SOCOM_UI.LOOKUP_RESOURCE_CATEGORY
UNION ALL
SELECT 'RESOURCE_CONSTRAINED_COA_2024' as table_name, COUNT(*) as row_count FROM SOCOM_UI.RESOURCE_CONSTRAINED_COA_2024
UNION ALL
SELECT 'ISS_SUMMARY_2024' as table_name, COUNT(*) as row_count FROM SOCOM_UI.ISS_SUMMARY_2024
UNION ALL
SELECT 'ISS_SUMMARY_2025' as table_name, COUNT(*) as row_count FROM SOCOM_UI.ISS_SUMMARY_2025;

-- Sample data from lookup tables
SELECT 'LOOKUP_PROGRAM Sample Data' as info;
SELECT * FROM SOCOM_UI.LOOKUP_PROGRAM LIMIT 5;

SELECT 'LOOKUP_SPONSOR Sample Data' as info;
SELECT * FROM SOCOM_UI.LOOKUP_SPONSOR LIMIT 5;

SELECT 'LOOKUP_RESOURCE_CATEGORY Sample Data' as info;
SELECT * FROM SOCOM_UI.LOOKUP_RESOURCE_CATEGORY LIMIT 5;

-- Check RESOURCE_CONSTRAINED_COA_2024 data
SELECT 'RESOURCE_CONSTRAINED_COA_2024 Data' as info;
SELECT * FROM SOCOM_UI.RESOURCE_CONSTRAINED_COA_2024;

-- Check for data consistency between lookup tables and main data
SELECT 'Data Consistency Check - PROGRAM_CODE' as info;
SELECT DISTINCT A.PROGRAM_CODE as 'Data in RESOURCE_CONSTRAINED_COA_2024'
FROM SOCOM_UI.RESOURCE_CONSTRAINED_COA_2024 A
WHERE A.PROGRAM_CODE NOT IN (SELECT PROGRAM_CODE FROM SOCOM_UI.LOOKUP_PROGRAM);

SELECT 'Data Consistency Check - CAPABILITY_SPONSOR_CODE' as info;
SELECT DISTINCT A.CAPABILITY_SPONSOR_CODE as 'Data in RESOURCE_CONSTRAINED_COA_2024'
FROM SOCOM_UI.RESOURCE_CONSTRAINED_COA_2024 A
WHERE A.CAPABILITY_SPONSOR_CODE NOT IN (SELECT SPONSOR_CODE FROM SOCOM_UI.LOOKUP_SPONSOR);

SELECT 'Data Consistency Check - RESOURCE_CATEGORY_CODE' as info;
SELECT DISTINCT A.RESOURCE_CATEGORY_CODE as 'Data in RESOURCE_CONSTRAINED_COA_2024'
FROM SOCOM_UI.RESOURCE_CONSTRAINED_COA_2024 A
WHERE A.RESOURCE_CATEGORY_CODE NOT IN (SELECT RESOURCE_CATEGORY_CODE FROM SOCOM_UI.LOOKUP_RESOURCE_CATEGORY);

-- Check database variables
SHOW VARIABLES LIKE 'sql_mode';
SHOW VARIABLES LIKE 'lower_case_table_names';
SHOW VARIABLES LIKE 'autocommit';

-- Check table sizes
SELECT 
    table_schema AS 'Database',
    table_name AS 'Table',
    ROUND(((data_length + index_length) / 1024 / 1024), 2) AS 'Size (MB)',
    table_rows as 'Estimated Rows'
FROM information_schema.TABLES 
WHERE table_schema = 'SOCOM_UI'
ORDER BY (data_length + index_length) DESC;

-- Check for any foreign key constraints
SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    CONSTRAINT_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = 'SOCOM_UI'
AND REFERENCED_TABLE_NAME IS NOT NULL;

-- Check for indexes on key columns
SHOW INDEX FROM SOCOM_UI.RESOURCE_CONSTRAINED_COA_2024;
SHOW INDEX FROM SOCOM_UI.LOOKUP_PROGRAM;
SHOW INDEX FROM SOCOM_UI.LOOKUP_SPONSOR;
SHOW INDEX FROM SOCOM_UI.LOOKUP_RESOURCE_CATEGORY;




