-- Rename ALL remaining lowercase 'id' columns to uppercase 'ID' to match application code
-- This fixes the "Unknown column 'ID' in 'field list'" error completely

USE SOCOM_UI;

-- Rename all remaining lowercase 'id' columns to uppercase 'ID'

-- LOOKUP tables
ALTER TABLE LOOKUP_ASSESSMENT_AREA CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE LOOKUP_PROGRAM CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE LOOKUP_PROGRAM_DETAIL CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE LOOKUP_RESOURCE_CATEGORY CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE LOOKUP_SPONSOR CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE LOOKUP_STORM CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;

-- USR tables
ALTER TABLE USR_DT_DIRTY_TABLE_EDIT_JOBS CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE USR_DT_LOOKUP_TABLE_METADATA CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE USR_ISSUE_AD_FINAL_SAVES CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE USR_ISSUE_AD_SAVES CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE USR_ISSUE_AO_SAVES CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE USR_LOOKUP_CYCLES_HISTORY CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE USR_LOOKUP_POM_POSITION_HISTORY CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE USR_LOOKUP_USER_CRITERIA_NAME CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE USR_LOOKUP_USER_CRITERIA_TERMS CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE USR_OPTION_SCORES CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE USR_ZBT_AD_SAVES CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE USR_ZBT_AO_SAVES CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;

-- Other tables
ALTER TABLE document_metadata CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE git_tracking CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE pipeline_mapping CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE processing_logs CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;
ALTER TABLE processing_pipeline CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;

-- Verify the changes - check a few key tables
SELECT 'LOOKUP_PROGRAM' as table_name, COLUMN_NAME as primary_key FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'SOCOM_UI' AND TABLE_NAME = 'LOOKUP_PROGRAM' AND COLUMN_KEY = 'PRI'
UNION ALL
SELECT 'USR_ZBT_AD_SAVES' as table_name, COLUMN_NAME as primary_key FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'SOCOM_UI' AND TABLE_NAME = 'USR_ZBT_AD_SAVES' AND COLUMN_KEY = 'PRI'
UNION ALL
SELECT 'document_metadata' as table_name, COLUMN_NAME as primary_key FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'SOCOM_UI' AND TABLE_NAME = 'document_metadata' AND COLUMN_KEY = 'PRI';


