-- Rename primary key columns from lowercase 'id' to uppercase 'ID' to match application code
-- This fixes the "Unknown column 'ID' in 'field list'" error

USE SOCOM_UI;

-- Rename id to ID in ZBT_SUMMARY_2024
ALTER TABLE ZBT_SUMMARY_2024 CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;

-- Rename id to ID in ZBT_SUMMARY_2025  
ALTER TABLE ZBT_SUMMARY_2025 CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;

-- Rename id to ID in ISS_SUMMARY_2024
ALTER TABLE ISS_SUMMARY_2024 CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;

-- Rename id to ID in ISS_SUMMARY_2025
ALTER TABLE ISS_SUMMARY_2025 CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;

-- Rename id to ID in POM_SUMMARY_2024
ALTER TABLE POM_SUMMARY_2024 CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;

-- Rename id to ID in POM_SUMMARY_2025
ALTER TABLE POM_SUMMARY_2025 CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;

-- Rename id to ID in RESOURCE_CONSTRAINED_COA_2024
ALTER TABLE RESOURCE_CONSTRAINED_COA_2024 CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;

-- Rename id to ID in RESOURCE_CONSTRAINED_COA_2025
ALTER TABLE RESOURCE_CONSTRAINED_COA_2025 CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;

-- Rename id to ID in DT_ZBT_EXTRACT_2024
ALTER TABLE DT_ZBT_EXTRACT_2024 CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;

-- Rename id to ID in DT_ZBT_EXTRACT_2025
ALTER TABLE DT_ZBT_EXTRACT_2025 CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;

-- Rename id to ID in DT_ISS_EXTRACT_2024
ALTER TABLE DT_ISS_EXTRACT_2024 CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;

-- Rename id to ID in DT_ISS_EXTRACT_2025
ALTER TABLE DT_ISS_EXTRACT_2025 CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;

-- Rename id to ID in DT_BUDGET_EXECUTION
ALTER TABLE DT_BUDGET_EXECUTION CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;

-- Rename id to ID in DT_PB_COMPARISON
ALTER TABLE DT_PB_COMPARISON CHANGE COLUMN `id` `ID` int NOT NULL AUTO_INCREMENT;

-- Rename ZBT_ID to ID in ZBT table
ALTER TABLE ZBT CHANGE COLUMN `ZBT_ID` `ID` int NOT NULL AUTO_INCREMENT;

-- Rename ISS_ID to ID in ISS table
ALTER TABLE ISS CHANGE COLUMN `ISS_ID` `ID` int NOT NULL AUTO_INCREMENT;

-- Rename POM_ID to ID in POM table
ALTER TABLE POM CHANGE COLUMN `POM_ID` `ID` int NOT NULL AUTO_INCREMENT;

-- Verify the changes
SELECT 'ZBT_SUMMARY_2024' as table_name, COLUMN_NAME as primary_key FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'SOCOM_UI' AND TABLE_NAME = 'ZBT_SUMMARY_2024' AND COLUMN_KEY = 'PRI'
UNION ALL
SELECT 'ZBT_SUMMARY_2025' as table_name, COLUMN_NAME as primary_key FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'SOCOM_UI' AND TABLE_NAME = 'ZBT_SUMMARY_2025' AND COLUMN_KEY = 'PRI'
UNION ALL
SELECT 'ZBT' as table_name, COLUMN_NAME as primary_key FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'SOCOM_UI' AND TABLE_NAME = 'ZBT' AND COLUMN_KEY = 'PRI';


