-- Create missing tables for SOCOM application
USE SOCOM_UI;

-- Create USR_CAP_USERS table
CREATE TABLE IF NOT EXISTS USR_CAP_USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    `GROUP` VARCHAR(255) NOT NULL,
    CREATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED TINYINT DEFAULT 0,
    UPDATE_USER INT NULL,
    INDEX idx_user_id (USER_ID),
    INDEX idx_group (`GROUP`),
    INDEX idx_is_deleted (IS_DELETED)
);

-- Create USR_CAP_USERS_HISTORY table
CREATE TABLE IF NOT EXISTS USR_CAP_USERS_HISTORY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CAP_USER_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    `GROUP` VARCHAR(255) NOT NULL,
    CREATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED TINYINT DEFAULT 0,
    UPDATE_USER INT NULL,
    INDEX idx_cap_user_id (CAP_USER_ID),
    INDEX idx_user_id (USER_ID)
);

-- Create USR_SITE_USERS table (needed by SOCOM_Site_User_model)
CREATE TABLE IF NOT EXISTS USR_SITE_USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    `GROUP` VARCHAR(255) NOT NULL,
    CREATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED TINYINT DEFAULT 0,
    UPDATE_USER INT NULL,
    INDEX idx_user_id (USER_ID),
    INDEX idx_group (`GROUP`),
    INDEX idx_is_deleted (IS_DELETED)
);

-- Create USR_SITE_USERS_HISTORY table
CREATE TABLE IF NOT EXISTS USR_SITE_USERS_HISTORY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SITE_USER_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    `GROUP` VARCHAR(255) NOT NULL,
    CREATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED TINYINT DEFAULT 0,
    UPDATE_USER INT NULL,
    INDEX idx_site_user_id (SITE_USER_ID),
    INDEX idx_user_id (USER_ID)
);

-- Insert a test user into USR_CAP_USERS (assuming user ID 1 exists in users table)
INSERT INTO USR_CAP_USERS (USER_ID, `GROUP`, IS_DELETED) 
VALUES (1, 'USSOCOM', 0) 
ON DUPLICATE KEY UPDATE `GROUP` = 'USSOCOM';
