-- =====================================================
-- SOCOM Database - Complete Schema with All Constraints
-- Fixed_Scripts_Database.sql
-- =====================================================

-- Drop existing database and recreate
DROP DATABASE IF EXISTS SOCOM_UI;
CREATE DATABASE SOCOM_UI CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE SOCOM_UI;

-- =====================================================
-- LOOKUP TABLES
-- =====================================================

-- Capability Sponsor Lookup
CREATE TABLE `LOOKUP_SPONSOR` (
  `SPONSOR_CODE` VARCHAR(50) NOT NULL,
  `SPONSOR_TITLE` VARCHAR(200) NOT NULL,
  `SPONSOR_DESCRIPTION` TEXT,
  `IS_ACTIVE` TINYINT(1) DEFAULT 1,
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`SPONSOR_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Assessment Area Lookup
CREATE TABLE `LOOKUP_ASSESSMENT_AREA` (
  `ASSESSMENT_AREA_CODE` VARCHAR(50) NOT NULL,
  `ASSESSMENT_AREA` VARCHAR(200) NOT NULL,
  `AREA_DESCRIPTION` TEXT,
  `IS_ACTIVE` TINYINT(1) DEFAULT 1,
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ASSESSMENT_AREA_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Program Lookup
CREATE TABLE `LOOKUP_PROGRAM` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PROGRAM_CODE` VARCHAR(50) NOT NULL,
  `PROGRAM_NAME` VARCHAR(200) NOT NULL,
  `PROGRAM_GROUP` VARCHAR(100),
  `CAPABILITY_SPONSOR_CODE` VARCHAR(50),
  `ASSESSMENT_AREA_CODE` VARCHAR(50),
  `POM_SPONSOR_CODE` VARCHAR(50),
  `EXECUTION_MANAGER_CODE` VARCHAR(50),
  `RESOURCE_CATEGORY_CODE` VARCHAR(50),
  `EOC_CODE` VARCHAR(50),
  `OSD_PROGRAM_ELEMENT_CODE` VARCHAR(100),
  `IS_ACTIVE` TINYINT(1) DEFAULT 1,
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_PROGRAM_CODE` (`PROGRAM_CODE`),
  KEY `IDX_CAPABILITY_SPONSOR` (`CAPABILITY_SPONSOR_CODE`),
  KEY `IDX_ASSESSMENT_AREA` (`ASSESSMENT_AREA_CODE`),
  KEY `IDX_PROGRAM_GROUP` (`PROGRAM_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Resource Category Lookup
CREATE TABLE `LOOKUP_RESOURCE_CATEGORY` (
  `CATEGORY_CODE` VARCHAR(50) NOT NULL,
  `CATEGORY_NAME` VARCHAR(200) NOT NULL,
  `CATEGORY_DESCRIPTION` TEXT,
  `IS_ACTIVE` TINYINT(1) DEFAULT 1,
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CATEGORY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- POM Position Decrement Lookup
CREATE TABLE `LOOKUP_POM_POSITION_DECREMENT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `POM_YEAR` INT NOT NULL,
  `POSITION` VARCHAR(50) NOT NULL,
  `DECREMENT_VALUE` DECIMAL(10,2),
  `DESCRIPTION` TEXT,
  `IS_ACTIVE` TINYINT(1) DEFAULT 1,
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_POM_POSITION` (`POM_YEAR`, `POSITION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- JCA Lookup
CREATE TABLE `LOOKUP_JCA` (
  `JCA_CODE` VARCHAR(50) NOT NULL,
  `JCA_NAME` VARCHAR(200) NOT NULL,
  `JCA_DESCRIPTION` TEXT,
  `IS_ACTIVE` TINYINT(1) DEFAULT 1,
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`JCA_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Tag Lookup
CREATE TABLE `LOOKUP_TAG` (
  `TAG_ID` INT NOT NULL AUTO_INCREMENT,
  `TAG_NAME` VARCHAR(100) NOT NULL,
  `TAG_DESCRIPTION` TEXT,
  `TAG_COLOR` VARCHAR(7),
  `IS_ACTIVE` TINYINT(1) DEFAULT 1,
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`TAG_ID`),
  UNIQUE KEY `UK_TAG_NAME` (`TAG_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- =====================================================
-- USER MANAGEMENT TABLES
-- =====================================================

-- User POM Position
CREATE TABLE `USR_LOOKUP_POM_POSITION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `POM_YEAR` INT NOT NULL,
  `POSITION` VARCHAR(50) NOT NULL,
  `IS_ACTIVE` TINYINT(1) DEFAULT 1,
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_POM_YEAR_POSITION` (`POM_YEAR`, `POSITION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- User Saved COA
CREATE TABLE `USR_LOOKUP_SAVED_COA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `COA_NAME` VARCHAR(200) NOT NULL,
  `COA_DESCRIPTION` TEXT,
  `COA_TYPE` VARCHAR(50) DEFAULT 'STANDARD' COMMENT 'Type of COA (STANDARD, RESOURCE_CONSTRAINED, etc.)',
  `USER_ID` INT,
  `IS_SHARED` TINYINT(1) DEFAULT 0,
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_USER_ID` (`USER_ID`),
  KEY `IDX_COA_TYPE` (`COA_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- User COA Management
CREATE TABLE `USR_LOOKUP_USER_SAVED_COA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `SAVED_COA_ID` INT NOT NULL,
  `CRITERIA_NAME_ID` INT,
  `COA_TITLE` VARCHAR(255) NOT NULL,
  `COA_DESCRIPTION` TEXT,
  `COA_TYPE` VARCHAR(50) DEFAULT 'STANDARD' COMMENT 'Type of COA (STANDARD, RESOURCE_CONSTRAINED, etc.)',
  `STATE` VARCHAR(50),
  `CREATED_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_USER_ID` (`USER_ID`),
  KEY `IDX_SAVED_COA_ID` (`SAVED_COA_ID`),
  KEY `IDX_COA_TYPE` (`COA_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- User Shared COA
CREATE TABLE `USR_LOOKUP_USER_SHARED_COA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ORIGINAL_USER_ID` INT NOT NULL,
  `NEW_USER_ID` INT NOT NULL,
  `ORIGINAL_COA_ID` INT NOT NULL,
  `NEW_COA_ID` INT NOT NULL,
  `COA_TYPE` VARCHAR(50) DEFAULT 'STANDARD' COMMENT 'Type of COA (STANDARD, RESOURCE_CONSTRAINED, etc.)',
  `IS_REVOKED` TINYINT DEFAULT 0,
  `CREATED_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_ORIGINAL_USER_ID` (`ORIGINAL_USER_ID`),
  KEY `IDX_NEW_USER_ID` (`NEW_USER_ID`),
  KEY `IDX_ORIGINAL_COA_ID` (`ORIGINAL_COA_ID`),
  KEY `IDX_NEW_COA_ID` (`NEW_COA_ID`),
  KEY `IDX_COA_TYPE` (`COA_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- User Option Scores
CREATE TABLE `USR_OPTION_SCORES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(200) NOT NULL,
  `DESCRIPTION` TEXT,
  `PROGRAM_ID` INT,
  `SESSION` VARCHAR(100),
  `USER_ID` INT,
  `CRITERIA_NAME_ID` INT,
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_PROGRAM_ID` (`PROGRAM_ID`),
  KEY `IDX_USER_ID` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- =====================================================
-- SCHEDULER TABLES
-- =====================================================

-- Scheduler
CREATE TABLE `USR_DT_SCHEDULER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CYCLE_ID` INT NOT NULL,
  `TYPE` ENUM('PROGRAM_SCORE_UPLOAD') NOT NULL DEFAULT 'PROGRAM_SCORE_UPLOAD',
  `CRON_STATUS` TINYINT(1) NOT NULL DEFAULT 0,
  `CRON_PROCESSED` TINYINT(1) NOT NULL DEFAULT 0,
  `ERRORS` VARCHAR(5000) NULL DEFAULT NULL,
  `WARNINGS` VARCHAR(5000) NULL DEFAULT NULL,
  `USER_ID` INT NOT NULL,
  `CREATED_TIMESTAMP` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_ADD_DATETIME` (`CREATED_TIMESTAMP`),
  KEY `IDX_ARCHIVE_FY` (`CRON_STATUS`,`TYPE`,`CREATED_TIMESTAMP`),
  KEY `IDX_CRON_STATUS_TYPE` (`CRON_STATUS`, `TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Scheduler Map
CREATE TABLE `USR_DT_SCHEDULER_MAP` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TYPE` ENUM('PROGRAM_SCORE_UPLOAD') NOT NULL DEFAULT 'PROGRAM_SCORE_UPLOAD',
  `DT_SCHEDULER_ID` INT NOT NULL,
  `MAP_ID` INT NOT NULL,
  `CREATED_TIMESTAMP` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_ADD_DATETIME` (`CREATED_TIMESTAMP`),
  KEY `IDX_ARCHIVE_FY` (`TYPE`,`CREATED_TIMESTAMP`),
  KEY `IDX_TYPE_CRON_STATUS_FISCAL_YEAR` (`TYPE`),
  KEY `IDX_DT_SCHEDULER_ID` (`DT_SCHEDULER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- =====================================================
-- POM TABLES
-- =====================================================

-- POM (Program Objective Memorandum) Table
CREATE TABLE `POM` (
  `POM_ID` INT NOT NULL AUTO_INCREMENT,
  `POM_YEAR` INT DEFAULT 2024,
  `POM_NAME` VARCHAR(255) NOT NULL,
  `POM_DESCRIPTION` TEXT,
  `POM_CATEGORY` ENUM('PERSONNEL','EQUIPMENT','TRAINING','INFRASTRUCTURE','TECHNOLOGY') DEFAULT 'PERSONNEL',
  `POM_PRIORITY` ENUM('CRITICAL','HIGH','MEDIUM','LOW') DEFAULT 'MEDIUM',
  `POM_STATUS` ENUM('IDENTIFIED','ANALYZING','APPROVED','FUNDED','IMPLEMENTED') DEFAULT 'IDENTIFIED',
  `POM_FUNDING_REQUIREMENT` DECIMAL(15,2),
  `POM_FUNDING_SOURCE` VARCHAR(255),
  `POM_IMPLEMENTATION_DATE` DATE,
  `POM_OWNER_ID` INT,
  `POM_CYCLE_ID` INT,
  `PB23` VARCHAR(50) DEFAULT NULL COMMENT 'PB23 Position Code',
  `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`POM_ID`),
  KEY `IDX_POM_YEAR` (`POM_YEAR`),
  KEY `IDX_POM_CATEGORY` (`POM_CATEGORY`),
  KEY `IDX_POM_PRIORITY` (`POM_PRIORITY`),
  KEY `IDX_POM_STATUS` (`POM_STATUS`),
  KEY `IDX_PB23` (`PB23`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- =====================================================
-- DATA TABLES - 2024
-- =====================================================

-- Resource Constrained COA 2024
CREATE TABLE `RESOURCE_CONSTRAINED_COA_2024` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CAPABILITY_SPONSOR_CODE` VARCHAR(50) NOT NULL,
  `EVENT_NAME` VARCHAR(200),
  `ASSESSMENT_AREA_CODE` VARCHAR(50) NOT NULL,
  `PROGRAM_NAME` VARCHAR(200) NOT NULL,
  `PROGRAM_CODE` VARCHAR(50) NOT NULL,
  `PROGRAM_GROUP` VARCHAR(100),
  `RESOURCE_CATEGORY_CODE` VARCHAR(50),
  `RESOURCE_K` DECIMAL(15,2),
  `POM_SPONSOR_CODE` VARCHAR(50),
  `EXECUTION_MANAGER_CODE` VARCHAR(50),
  `EOC_CODE` VARCHAR(50),
  `OSD_PROGRAM_ELEMENT_CODE` VARCHAR(100),
  `DELTA_AMT` DECIMAL(15,2),
  `FISCAL_YEAR` INT,
  `WEIGHTED_SCORE` DECIMAL(5,2),
  `STORM_SCORE` DECIMAL(5,2),
  `POM_CYCLE_OPTIMIZATION_TYPE` ENUM('Issue Optimization', 'Resource Constraining'),
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_CAPABILITY_SPONSOR` (`CAPABILITY_SPONSOR_CODE`),
  KEY `IDX_ASSESSMENT_AREA` (`ASSESSMENT_AREA_CODE`),
  KEY `IDX_PROGRAM_CODE` (`PROGRAM_CODE`),
  KEY `IDX_EVENT_NAME` (`EVENT_NAME`),
  KEY `IDX_FISCAL_YEAR` (`FISCAL_YEAR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Resource Constrained COA 2025
CREATE TABLE `RESOURCE_CONSTRAINED_COA_2025` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CAPABILITY_SPONSOR_CODE` VARCHAR(50) NOT NULL,
  `EVENT_NAME` VARCHAR(200),
  `ASSESSMENT_AREA_CODE` VARCHAR(50) NOT NULL,
  `PROGRAM_NAME` VARCHAR(200) NOT NULL,
  `PROGRAM_CODE` VARCHAR(50) NOT NULL,
  `PROGRAM_GROUP` VARCHAR(100),
  `RESOURCE_CATEGORY_CODE` VARCHAR(50),
  `RESOURCE_K` DECIMAL(15,2),
  `POM_SPONSOR_CODE` VARCHAR(50),
  `EXECUTION_MANAGER_CODE` VARCHAR(50),
  `EOC_CODE` VARCHAR(50),
  `OSD_PROGRAM_ELEMENT_CODE` VARCHAR(100),
  `DELTA_AMT` DECIMAL(15,2),
  `FISCAL_YEAR` INT,
  `WEIGHTED_SCORE` DECIMAL(5,2),
  `STORM_SCORE` DECIMAL(5,2),
  `POM_CYCLE_OPTIMIZATION_TYPE` ENUM('Issue Optimization', 'Resource Constraining'),
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_CAPABILITY_SPONSOR` (`CAPABILITY_SPONSOR_CODE`),
  KEY `IDX_ASSESSMENT_AREA` (`ASSESSMENT_AREA_CODE`),
  KEY `IDX_PROGRAM_CODE` (`PROGRAM_CODE`),
  KEY `IDX_EVENT_NAME` (`EVENT_NAME`),
  KEY `IDX_FISCAL_YEAR` (`FISCAL_YEAR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- PB Comparison Data
CREATE TABLE `DT_PB_COMPARISON` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CAPABILITY_SPONSOR_CODE` VARCHAR(50) NOT NULL,
  `ASSESSMENT_AREA_CODE` VARCHAR(50) NOT NULL,
  `PROGRAM_CODE` VARCHAR(50) NOT NULL,
  `PROGRAM_GROUP` VARCHAR(100),
  `RESOURCE_CATEGORY_CODE` VARCHAR(50),
  `FISCAL_YEAR` INT,
  `BUDGET_AMOUNT` DECIMAL(15,2),
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_CAPABILITY_SPONSOR` (`CAPABILITY_SPONSOR_CODE`),
  KEY `IDX_ASSESSMENT_AREA` (`ASSESSMENT_AREA_CODE`),
  KEY `IDX_PROGRAM_CODE` (`PROGRAM_CODE`),
  KEY `IDX_FISCAL_YEAR` (`FISCAL_YEAR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Budget Execution Data
CREATE TABLE `DT_BUDGET_EXECUTION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CAPABILITY_SPONSOR_CODE` VARCHAR(50) NOT NULL,
  `ASSESSMENT_AREA_CODE` VARCHAR(50) NOT NULL,
  `PROGRAM_CODE` VARCHAR(50) NOT NULL,
  `PROGRAM_GROUP` VARCHAR(100),
  `RESOURCE_CATEGORY_CODE` VARCHAR(50),
  `EOC_CODE` VARCHAR(50),
  `EXECUTION_MANAGER_CODE` VARCHAR(50),
  `OSD_PROGRAM_ELEMENT_CODE` VARCHAR(100),
  `FISCAL_YEAR` INT,
  `EXECUTED_AMOUNT` DECIMAL(15,2),
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_CAPABILITY_SPONSOR` (`CAPABILITY_SPONSOR_CODE`),
  KEY `IDX_ASSESSMENT_AREA` (`ASSESSMENT_AREA_CODE`),
  KEY `IDX_PROGRAM_CODE` (`PROGRAM_CODE`),
  KEY `IDX_FISCAL_YEAR` (`FISCAL_YEAR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- AMS FEM Data
CREATE TABLE `DT_AMS_FEM` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PROGRAM_GROUP` VARCHAR(100),
  `CAPABILITY_SPONSOR_CODE` VARCHAR(50),
  `ASSESSMENT_AREA_CODE` VARCHAR(50),
  `APPN` VARCHAR(50),
  `ELEMENT_OF_COST` VARCHAR(100),
  `EXECUTION_MANAGER_CODE` VARCHAR(50),
  `PE` VARCHAR(50),
  `FISCAL_YEAR` INT,
  `AMOUNT` DECIMAL(15,2),
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_PROGRAM_GROUP` (`PROGRAM_GROUP`),
  KEY `IDX_CAPABILITY_SPONSOR` (`CAPABILITY_SPONSOR_CODE`),
  KEY `IDX_ASSESSMENT_AREA` (`ASSESSMENT_AREA_CODE`),
  KEY `IDX_FISCAL_YEAR` (`FISCAL_YEAR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ISS Extract 2024
CREATE TABLE `DT_ISS_EXTRACT_2024` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PROGRAM_GROUP` VARCHAR(100),
  `CAPABILITY_SPONSOR_CODE` VARCHAR(50),
  `ASSESSMENT_AREA_CODE` VARCHAR(50),
  `PROGRAM_CODE` VARCHAR(50),
  `FISCAL_YEAR` INT,
  `AMOUNT` DECIMAL(15,2),
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_PROGRAM_GROUP` (`PROGRAM_GROUP`),
  KEY `IDX_CAPABILITY_SPONSOR` (`CAPABILITY_SPONSOR_CODE`),
  KEY `IDX_ASSESSMENT_AREA` (`ASSESSMENT_AREA_CODE`),
  KEY `IDX_PROGRAM_CODE` (`PROGRAM_CODE`),
  KEY `IDX_FISCAL_YEAR` (`FISCAL_YEAR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ISS Extract 2025
CREATE TABLE `DT_ISS_EXTRACT_2025` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PROGRAM_GROUP` VARCHAR(100),
  `CAPABILITY_SPONSOR_CODE` VARCHAR(50),
  `ASSESSMENT_AREA_CODE` VARCHAR(50),
  `PROGRAM_CODE` VARCHAR(50),
  `FISCAL_YEAR` INT,
  `AMOUNT` DECIMAL(15,2),
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_PROGRAM_GROUP` (`PROGRAM_GROUP`),
  KEY `IDX_CAPABILITY_SPONSOR` (`CAPABILITY_SPONSOR_CODE`),
  KEY `IDX_ASSESSMENT_AREA` (`ASSESSMENT_AREA_CODE`),
  KEY `IDX_PROGRAM_CODE` (`PROGRAM_CODE`),
  KEY `IDX_FISCAL_YEAR` (`FISCAL_YEAR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ZBT Extract 2024
CREATE TABLE `DT_ZBT_EXTRACT_2024` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PROGRAM_GROUP` VARCHAR(100),
  `CAPABILITY_SPONSOR_CODE` VARCHAR(50),
  `ASSESSMENT_AREA_CODE` VARCHAR(50),
  `PROGRAM_CODE` VARCHAR(50),
  `FISCAL_YEAR` INT,
  `AMOUNT` DECIMAL(15,2),
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_PROGRAM_GROUP` (`PROGRAM_GROUP`),
  KEY `IDX_CAPABILITY_SPONSOR` (`CAPABILITY_SPONSOR_CODE`),
  KEY `IDX_ASSESSMENT_AREA` (`ASSESSMENT_AREA_CODE`),
  KEY `IDX_PROGRAM_CODE` (`PROGRAM_CODE`),
  KEY `IDX_FISCAL_YEAR` (`FISCAL_YEAR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ZBT Extract 2025
CREATE TABLE `DT_ZBT_EXTRACT_2025` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PROGRAM_GROUP` VARCHAR(100),
  `CAPABILITY_SPONSOR_CODE` VARCHAR(50),
  `ASSESSMENT_AREA_CODE` VARCHAR(50),
  `PROGRAM_CODE` VARCHAR(50),
  `FISCAL_YEAR` INT,
  `AMOUNT` DECIMAL(15,2),
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_PROGRAM_GROUP` (`PROGRAM_GROUP`),
  KEY `IDX_CAPABILITY_SPONSOR` (`CAPABILITY_SPONSOR_CODE`),
  KEY `IDX_ASSESSMENT_AREA` (`ASSESSMENT_AREA_CODE`),
  KEY `IDX_PROGRAM_CODE` (`PROGRAM_CODE`),
  KEY `IDX_FISCAL_YEAR` (`FISCAL_YEAR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ISS Summary 2024
CREATE TABLE `ISS_SUMMARY_2024` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PROGRAM_GROUP` VARCHAR(100),
  `CAPABILITY_SPONSOR_CODE` VARCHAR(50),
  `ASSESSMENT_AREA_CODE` VARCHAR(50),
  `PROGRAM_CODE` VARCHAR(50),
  `FISCAL_YEAR` INT,
  `TOTAL_AMOUNT` DECIMAL(15,2),
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_PROGRAM_GROUP` (`PROGRAM_GROUP`),
  KEY `IDX_CAPABILITY_SPONSOR` (`CAPABILITY_SPONSOR_CODE`),
  KEY `IDX_ASSESSMENT_AREA` (`ASSESSMENT_AREA_CODE`),
  KEY `IDX_PROGRAM_CODE` (`PROGRAM_CODE`),
  KEY `IDX_FISCAL_YEAR` (`FISCAL_YEAR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ISS Summary 2025
CREATE TABLE `ISS_SUMMARY_2025` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PROGRAM_GROUP` VARCHAR(100),
  `CAPABILITY_SPONSOR_CODE` VARCHAR(50),
  `ASSESSMENT_AREA_CODE` VARCHAR(50),
  `PROGRAM_CODE` VARCHAR(50),
  `FISCAL_YEAR` INT,
  `TOTAL_AMOUNT` DECIMAL(15,2),
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_PROGRAM_GROUP` (`PROGRAM_GROUP`),
  KEY `IDX_CAPABILITY_SPONSOR` (`CAPABILITY_SPONSOR_CODE`),
  KEY `IDX_ASSESSMENT_AREA` (`ASSESSMENT_AREA_CODE`),
  KEY `IDX_PROGRAM_CODE` (`PROGRAM_CODE`),
  KEY `IDX_FISCAL_YEAR` (`FISCAL_YEAR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ZBT Summary 2024
CREATE TABLE `ZBT_SUMMARY_2024` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PROGRAM_GROUP` VARCHAR(100),
  `CAPABILITY_SPONSOR_CODE` VARCHAR(50),
  `ASSESSMENT_AREA_CODE` VARCHAR(50),
  `PROGRAM_CODE` VARCHAR(50),
  `FISCAL_YEAR` INT,
  `TOTAL_AMOUNT` DECIMAL(15,2),
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_PROGRAM_GROUP` (`PROGRAM_GROUP`),
  KEY `IDX_CAPABILITY_SPONSOR` (`CAPABILITY_SPONSOR_CODE`),
  KEY `IDX_ASSESSMENT_AREA` (`ASSESSMENT_AREA_CODE`),
  KEY `IDX_PROGRAM_CODE` (`PROGRAM_CODE`),
  KEY `IDX_FISCAL_YEAR` (`FISCAL_YEAR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ZBT Summary 2025
CREATE TABLE `ZBT_SUMMARY_2025` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PROGRAM_GROUP` VARCHAR(100),
  `CAPABILITY_SPONSOR_CODE` VARCHAR(50),
  `ASSESSMENT_AREA_CODE` VARCHAR(50),
  `PROGRAM_CODE` VARCHAR(50),
  `FISCAL_YEAR` INT,
  `TOTAL_AMOUNT` DECIMAL(15,2),
  `CREATED_TIMESTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_PROGRAM_GROUP` (`PROGRAM_GROUP`),
  KEY `IDX_CAPABILITY_SPONSOR` (`CAPABILITY_SPONSOR_CODE`),
  KEY `IDX_ASSESSMENT_AREA` (`ASSESSMENT_AREA_CODE`),
  KEY `IDX_PROGRAM_CODE` (`PROGRAM_CODE`),
  KEY `IDX_FISCAL_YEAR` (`FISCAL_YEAR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- =====================================================
-- FOREIGN KEY CONSTRAINTS
-- =====================================================

-- Program Lookup Foreign Keys
ALTER TABLE `LOOKUP_PROGRAM` 
ADD CONSTRAINT `FK_PROGRAM_CAPABILITY_SPONSOR` 
FOREIGN KEY (`CAPABILITY_SPONSOR_CODE`) REFERENCES `LOOKUP_SPONSOR`(`SPONSOR_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `LOOKUP_PROGRAM` 
ADD CONSTRAINT `FK_PROGRAM_ASSESSMENT_AREA` 
FOREIGN KEY (`ASSESSMENT_AREA_CODE`) REFERENCES `LOOKUP_ASSESSMENT_AREA`(`ASSESSMENT_AREA_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `LOOKUP_PROGRAM` 
ADD CONSTRAINT `FK_PROGRAM_RESOURCE_CATEGORY` 
FOREIGN KEY (`RESOURCE_CATEGORY_CODE`) REFERENCES `LOOKUP_RESOURCE_CATEGORY`(`CATEGORY_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- Resource Constrained COA 2024 Foreign Keys
ALTER TABLE `RESOURCE_CONSTRAINED_COA_2024` 
ADD CONSTRAINT `FK_RC_COA_2024_CAPABILITY_SPONSOR` 
FOREIGN KEY (`CAPABILITY_SPONSOR_CODE`) REFERENCES `LOOKUP_SPONSOR`(`SPONSOR_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `RESOURCE_CONSTRAINED_COA_2024` 
ADD CONSTRAINT `FK_RC_COA_2024_ASSESSMENT_AREA` 
FOREIGN KEY (`ASSESSMENT_AREA_CODE`) REFERENCES `LOOKUP_ASSESSMENT_AREA`(`ASSESSMENT_AREA_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `RESOURCE_CONSTRAINED_COA_2024` 
ADD CONSTRAINT `FK_RC_COA_2024_PROGRAM_CODE` 
FOREIGN KEY (`PROGRAM_CODE`) REFERENCES `LOOKUP_PROGRAM`(`PROGRAM_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `RESOURCE_CONSTRAINED_COA_2024` 
ADD CONSTRAINT `FK_RC_COA_2024_RESOURCE_CATEGORY` 
FOREIGN KEY (`RESOURCE_CATEGORY_CODE`) REFERENCES `LOOKUP_RESOURCE_CATEGORY`(`CATEGORY_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- Resource Constrained COA 2025 Foreign Keys
ALTER TABLE `RESOURCE_CONSTRAINED_COA_2025` 
ADD CONSTRAINT `FK_RC_COA_2025_CAPABILITY_SPONSOR` 
FOREIGN KEY (`CAPABILITY_SPONSOR_CODE`) REFERENCES `LOOKUP_SPONSOR`(`SPONSOR_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `RESOURCE_CONSTRAINED_COA_2025` 
ADD CONSTRAINT `FK_RC_COA_2025_ASSESSMENT_AREA` 
FOREIGN KEY (`ASSESSMENT_AREA_CODE`) REFERENCES `LOOKUP_ASSESSMENT_AREA`(`ASSESSMENT_AREA_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `RESOURCE_CONSTRAINED_COA_2025` 
ADD CONSTRAINT `FK_RC_COA_2025_PROGRAM_CODE` 
FOREIGN KEY (`PROGRAM_CODE`) REFERENCES `LOOKUP_PROGRAM`(`PROGRAM_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `RESOURCE_CONSTRAINED_COA_2025` 
ADD CONSTRAINT `FK_RC_COA_2025_RESOURCE_CATEGORY` 
FOREIGN KEY (`RESOURCE_CATEGORY_CODE`) REFERENCES `LOOKUP_RESOURCE_CATEGORY`(`CATEGORY_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- PB Comparison Foreign Keys
ALTER TABLE `DT_PB_COMPARISON` 
ADD CONSTRAINT `FK_PB_COMP_CAPABILITY_SPONSOR` 
FOREIGN KEY (`CAPABILITY_SPONSOR_CODE`) REFERENCES `LOOKUP_SPONSOR`(`SPONSOR_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `DT_PB_COMPARISON` 
ADD CONSTRAINT `FK_PB_COMP_ASSESSMENT_AREA` 
FOREIGN KEY (`ASSESSMENT_AREA_CODE`) REFERENCES `LOOKUP_ASSESSMENT_AREA`(`ASSESSMENT_AREA_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `DT_PB_COMPARISON` 
ADD CONSTRAINT `FK_PB_COMP_PROGRAM_CODE` 
FOREIGN KEY (`PROGRAM_CODE`) REFERENCES `LOOKUP_PROGRAM`(`PROGRAM_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `DT_PB_COMPARISON` 
ADD CONSTRAINT `FK_PB_COMP_RESOURCE_CATEGORY` 
FOREIGN KEY (`RESOURCE_CATEGORY_CODE`) REFERENCES `LOOKUP_RESOURCE_CATEGORY`(`CATEGORY_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- Budget Execution Foreign Keys
ALTER TABLE `DT_BUDGET_EXECUTION` 
ADD CONSTRAINT `FK_BUDGET_EXEC_CAPABILITY_SPONSOR` 
FOREIGN KEY (`CAPABILITY_SPONSOR_CODE`) REFERENCES `LOOKUP_SPONSOR`(`SPONSOR_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `DT_BUDGET_EXECUTION` 
ADD CONSTRAINT `FK_BUDGET_EXEC_ASSESSMENT_AREA` 
FOREIGN KEY (`ASSESSMENT_AREA_CODE`) REFERENCES `LOOKUP_ASSESSMENT_AREA`(`ASSESSMENT_AREA_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `DT_BUDGET_EXECUTION` 
ADD CONSTRAINT `FK_BUDGET_EXEC_PROGRAM_CODE` 
FOREIGN KEY (`PROGRAM_CODE`) REFERENCES `LOOKUP_PROGRAM`(`PROGRAM_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `DT_BUDGET_EXECUTION` 
ADD CONSTRAINT `FK_BUDGET_EXEC_RESOURCE_CATEGORY` 
FOREIGN KEY (`RESOURCE_CATEGORY_CODE`) REFERENCES `LOOKUP_RESOURCE_CATEGORY`(`CATEGORY_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AMS FEM Foreign Keys
ALTER TABLE `DT_AMS_FEM` 
ADD CONSTRAINT `FK_AMS_FEM_CAPABILITY_SPONSOR` 
FOREIGN KEY (`CAPABILITY_SPONSOR_CODE`) REFERENCES `LOOKUP_SPONSOR`(`SPONSOR_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `DT_AMS_FEM` 
ADD CONSTRAINT `FK_AMS_FEM_ASSESSMENT_AREA` 
FOREIGN KEY (`ASSESSMENT_AREA_CODE`) REFERENCES `LOOKUP_ASSESSMENT_AREA`(`ASSESSMENT_AREA_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- ISS Extract 2024 Foreign Keys
ALTER TABLE `DT_ISS_EXTRACT_2024` 
ADD CONSTRAINT `FK_ISS_2024_CAPABILITY_SPONSOR` 
FOREIGN KEY (`CAPABILITY_SPONSOR_CODE`) REFERENCES `LOOKUP_SPONSOR`(`SPONSOR_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `DT_ISS_EXTRACT_2024` 
ADD CONSTRAINT `FK_ISS_2024_ASSESSMENT_AREA` 
FOREIGN KEY (`ASSESSMENT_AREA_CODE`) REFERENCES `LOOKUP_ASSESSMENT_AREA`(`ASSESSMENT_AREA_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `DT_ISS_EXTRACT_2024` 
ADD CONSTRAINT `FK_ISS_2024_PROGRAM_CODE` 
FOREIGN KEY (`PROGRAM_CODE`) REFERENCES `LOOKUP_PROGRAM`(`PROGRAM_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- ISS Extract 2025 Foreign Keys
ALTER TABLE `DT_ISS_EXTRACT_2025` 
ADD CONSTRAINT `FK_ISS_2025_CAPABILITY_SPONSOR` 
FOREIGN KEY (`CAPABILITY_SPONSOR_CODE`) REFERENCES `LOOKUP_SPONSOR`(`SPONSOR_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `DT_ISS_EXTRACT_2025` 
ADD CONSTRAINT `FK_ISS_2025_ASSESSMENT_AREA` 
FOREIGN KEY (`ASSESSMENT_AREA_CODE`) REFERENCES `LOOKUP_ASSESSMENT_AREA`(`ASSESSMENT_AREA_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `DT_ISS_EXTRACT_2025` 
ADD CONSTRAINT `FK_ISS_2025_PROGRAM_CODE` 
FOREIGN KEY (`PROGRAM_CODE`) REFERENCES `LOOKUP_PROGRAM`(`PROGRAM_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- ZBT Extract 2024 Foreign Keys
ALTER TABLE `DT_ZBT_EXTRACT_2024` 
ADD CONSTRAINT `FK_ZBT_2024_CAPABILITY_SPONSOR` 
FOREIGN KEY (`CAPABILITY_SPONSOR_CODE`) REFERENCES `LOOKUP_SPONSOR`(`SPONSOR_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `DT_ZBT_EXTRACT_2024` 
ADD CONSTRAINT `FK_ZBT_2024_ASSESSMENT_AREA` 
FOREIGN KEY (`ASSESSMENT_AREA_CODE`) REFERENCES `LOOKUP_ASSESSMENT_AREA`(`ASSESSMENT_AREA_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `DT_ZBT_EXTRACT_2024` 
ADD CONSTRAINT `FK_ZBT_2024_PROGRAM_CODE` 
FOREIGN KEY (`PROGRAM_CODE`) REFERENCES `LOOKUP_PROGRAM`(`PROGRAM_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- ZBT Extract 2025 Foreign Keys
ALTER TABLE `DT_ZBT_EXTRACT_2025` 
ADD CONSTRAINT `FK_ZBT_2025_CAPABILITY_SPONSOR` 
FOREIGN KEY (`CAPABILITY_SPONSOR_CODE`) REFERENCES `LOOKUP_SPONSOR`(`SPONSOR_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `DT_ZBT_EXTRACT_2025` 
ADD CONSTRAINT `FK_ZBT_2025_ASSESSMENT_AREA` 
FOREIGN KEY (`ASSESSMENT_AREA_CODE`) REFERENCES `LOOKUP_ASSESSMENT_AREA`(`ASSESSMENT_AREA_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `DT_ZBT_EXTRACT_2025` 
ADD CONSTRAINT `FK_ZBT_2025_PROGRAM_CODE` 
FOREIGN KEY (`PROGRAM_CODE`) REFERENCES `LOOKUP_PROGRAM`(`PROGRAM_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- Summary Tables Foreign Keys (ISS 2024)
ALTER TABLE `ISS_SUMMARY_2024` 
ADD CONSTRAINT `FK_ISS_SUMMARY_2024_CAPABILITY_SPONSOR` 
FOREIGN KEY (`CAPABILITY_SPONSOR_CODE`) REFERENCES `LOOKUP_SPONSOR`(`SPONSOR_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `ISS_SUMMARY_2024` 
ADD CONSTRAINT `FK_ISS_SUMMARY_2024_ASSESSMENT_AREA` 
FOREIGN KEY (`ASSESSMENT_AREA_CODE`) REFERENCES `LOOKUP_ASSESSMENT_AREA`(`ASSESSMENT_AREA_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `ISS_SUMMARY_2024` 
ADD CONSTRAINT `FK_ISS_SUMMARY_2024_PROGRAM_CODE` 
FOREIGN KEY (`PROGRAM_CODE`) REFERENCES `LOOKUP_PROGRAM`(`PROGRAM_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- Summary Tables Foreign Keys (ISS 2025)
ALTER TABLE `ISS_SUMMARY_2025` 
ADD CONSTRAINT `FK_ISS_SUMMARY_2025_CAPABILITY_SPONSOR` 
FOREIGN KEY (`CAPABILITY_SPONSOR_CODE`) REFERENCES `LOOKUP_SPONSOR`(`SPONSOR_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `ISS_SUMMARY_2025` 
ADD CONSTRAINT `FK_ISS_SUMMARY_2025_ASSESSMENT_AREA` 
FOREIGN KEY (`ASSESSMENT_AREA_CODE`) REFERENCES `LOOKUP_ASSESSMENT_AREA`(`ASSESSMENT_AREA_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `ISS_SUMMARY_2025` 
ADD CONSTRAINT `FK_ISS_SUMMARY_2025_PROGRAM_CODE` 
FOREIGN KEY (`PROGRAM_CODE`) REFERENCES `LOOKUP_PROGRAM`(`PROGRAM_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- Summary Tables Foreign Keys (ZBT 2024)
ALTER TABLE `ZBT_SUMMARY_2024` 
ADD CONSTRAINT `FK_ZBT_SUMMARY_2024_CAPABILITY_SPONSOR` 
FOREIGN KEY (`CAPABILITY_SPONSOR_CODE`) REFERENCES `LOOKUP_SPONSOR`(`SPONSOR_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `ZBT_SUMMARY_2024` 
ADD CONSTRAINT `FK_ZBT_SUMMARY_2024_ASSESSMENT_AREA` 
FOREIGN KEY (`ASSESSMENT_AREA_CODE`) REFERENCES `LOOKUP_ASSESSMENT_AREA`(`ASSESSMENT_AREA_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `ZBT_SUMMARY_2024` 
ADD CONSTRAINT `FK_ZBT_SUMMARY_2024_PROGRAM_CODE` 
FOREIGN KEY (`PROGRAM_CODE`) REFERENCES `LOOKUP_PROGRAM`(`PROGRAM_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- Summary Tables Foreign Keys (ZBT 2025)
ALTER TABLE `ZBT_SUMMARY_2025` 
ADD CONSTRAINT `FK_ZBT_SUMMARY_2025_CAPABILITY_SPONSOR` 
FOREIGN KEY (`CAPABILITY_SPONSOR_CODE`) REFERENCES `LOOKUP_SPONSOR`(`SPONSOR_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `ZBT_SUMMARY_2025` 
ADD CONSTRAINT `FK_ZBT_SUMMARY_2025_ASSESSMENT_AREA` 
FOREIGN KEY (`ASSESSMENT_AREA_CODE`) REFERENCES `LOOKUP_ASSESSMENT_AREA`(`ASSESSMENT_AREA_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `ZBT_SUMMARY_2025` 
ADD CONSTRAINT `FK_ZBT_SUMMARY_2025_PROGRAM_CODE` 
FOREIGN KEY (`PROGRAM_CODE`) REFERENCES `LOOKUP_PROGRAM`(`PROGRAM_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- Scheduler Foreign Keys
ALTER TABLE `USR_DT_SCHEDULER_MAP` 
ADD CONSTRAINT `FK_SCHEDULER_MAP_SCHEDULER` 
FOREIGN KEY (`DT_SCHEDULER_ID`) REFERENCES `USR_DT_SCHEDULER`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- =====================================================
-- END OF SCHEMA
-- =====================================================

-- =====================================================
-- CHANGELOG - Missing Columns Added (2025-09-01)
-- =====================================================
-- Added missing columns identified from error logs:
-- 1. COA_TYPE column added to USR_LOOKUP_SAVED_COA table
-- 2. COA_TYPE column added to USR_LOOKUP_USER_SAVED_COA table  
-- 3. COA_TYPE column added to USR_LOOKUP_USER_SHARED_COA table
-- 4. PB23 column added to POM table
-- 5. Updated table structures to match current database schema
-- 6. Added proper indexes for performance optimization
-- 
-- These changes resolve DataTables Ajax errors caused by missing columns:
-- - "Unknown column 'user_saved.COA_TYPE' in 'field list'"
-- - "Unknown column 'PB23' in 'field list'"
-- - "Requested unknown parameter '0' for row 0, column 0" (DataTables error)
-- =====================================================

