-- SOCOM Database Setup Script - Simplified Version
-- This script creates the required database and tables for the SOCOM system

USE rhombus_db;

-- Create ZBT Summary tables for different years
CREATE TABLE IF NOT EXISTS ZBT_SUMMARY_2024 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    CAPABILITY_SPONSOR_CODE VARCHAR(255) NOT NULL,
    EVENT_NAME VARCHAR(500) NOT NULL,
    DELTA_AMT DECIMAL(15,2) DEFAULT 0.00,
    FISCAL_YEAR INT DEFAULT 2024,
    PROGRAM_NAME VARCHAR(500),
    RESOURCE_CATEGORY_CODE VARCHAR(100),
    EXECUTION_MANAGER_CODE VARCHAR(100),
    PROGRAM_CODE VARCHAR(100),
    EOC_CODE VARCHAR(100),
    OSD_PE_CODE VARCHAR(100),
    APPROVAL_STATUS VARCHAR(50) DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_capability_sponsor (CAPABILITY_SPONSOR_CODE),
    INDEX idx_event_name (EVENT_NAME),
    INDEX idx_fiscal_year (FISCAL_YEAR),
    INDEX idx_program_name (PROGRAM_NAME)
);

CREATE TABLE IF NOT EXISTS ZBT_SUMMARY_2025 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    CAPABILITY_SPONSOR_CODE VARCHAR(255) NOT NULL,
    EVENT_NAME VARCHAR(500) NOT NULL,
    DELTA_AMT DECIMAL(15,2) DEFAULT 0.00,
    FISCAL_YEAR INT DEFAULT 2025,
    PROGRAM_NAME VARCHAR(500),
    RESOURCE_CATEGORY_CODE VARCHAR(100),
    EXECUTION_MANAGER_CODE VARCHAR(100),
    PROGRAM_CODE VARCHAR(100),
    EOC_CODE VARCHAR(100),
    OSD_PE_CODE VARCHAR(100),
    APPROVAL_STATUS VARCHAR(50) DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_capability_sponsor (CAPABILITY_SPONSOR_CODE),
    INDEX idx_event_name (EVENT_NAME),
    INDEX idx_fiscal_year (FISCAL_YEAR),
    INDEX idx_program_name (PROGRAM_NAME)
);

-- Create Issue Summary tables for different years
CREATE TABLE IF NOT EXISTS ISS_SUMMARY_2024 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    CAPABILITY_SPONSOR_CODE VARCHAR(255) NOT NULL,
    EVENT_NAME VARCHAR(500) NOT NULL,
    DELTA_AMT DECIMAL(15,2) DEFAULT 0.00,
    FISCAL_YEAR INT DEFAULT 2024,
    PROGRAM_NAME VARCHAR(500),
    RESOURCE_CATEGORY_CODE VARCHAR(100),
    EXECUTION_MANAGER_CODE VARCHAR(100),
    PROGRAM_CODE VARCHAR(100),
    EOC_CODE VARCHAR(100),
    OSD_PE_CODE VARCHAR(100),
    APPROVAL_STATUS VARCHAR(50) DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_capability_sponsor (CAPABILITY_SPONSOR_CODE),
    INDEX idx_event_name (EVENT_NAME),
    INDEX idx_fiscal_year (FISCAL_YEAR),
    INDEX idx_program_name (PROGRAM_NAME)
);

CREATE TABLE IF NOT EXISTS ISS_SUMMARY_2025 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    CAPABILITY_SPONSOR_CODE VARCHAR(255) NOT NULL,
    EVENT_NAME VARCHAR(500) NOT NULL,
    DELTA_AMT DECIMAL(15,2) DEFAULT 0.00,
    FISCAL_YEAR INT DEFAULT 2025,
    PROGRAM_NAME VARCHAR(500),
    RESOURCE_CATEGORY_CODE VARCHAR(100),
    EXECUTION_MANAGER_CODE VARCHAR(100),
    PROGRAM_CODE VARCHAR(100),
    EOC_CODE VARCHAR(100),
    OSD_PE_CODE VARCHAR(100),
    APPROVAL_STATUS VARCHAR(50) DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_capability_sponsor (CAPABILITY_SPONSOR_CODE),
    INDEX idx_event_name (EVENT_NAME),
    INDEX idx_fiscal_year (FISCAL_YEAR),
    INDEX idx_program_name (PROGRAM_NAME)
);

-- Create lookup tables for reference data
CREATE TABLE IF NOT EXISTS LOOKUP_SPONSOR (
    id INT AUTO_INCREMENT PRIMARY KEY,
    SPONSOR_CODE VARCHAR(100) UNIQUE NOT NULL,
    SPONSOR_NAME VARCHAR(255) NOT NULL,
    SPONSOR_TYPE ENUM('CAPABILITY', 'POM') NOT NULL,
    ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_sponsor_code (SPONSOR_CODE),
    INDEX idx_sponsor_type (SPONSOR_TYPE)
);

CREATE TABLE IF NOT EXISTS LOOKUP_ASSESSMENT_AREA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    AREA_CODE VARCHAR(100) UNIQUE NOT NULL,
    AREA_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_area_code (AREA_CODE)
);

CREATE TABLE IF NOT EXISTS LOOKUP_RESOURCE_CATEGORY (
    id INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_CODE VARCHAR(100) UNIQUE NOT NULL,
    CATEGORY_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_category_code (CATEGORY_CODE)
);

-- Insert basic lookup data
INSERT IGNORE INTO LOOKUP_SPONSOR (SPONSOR_CODE, SPONSOR_NAME, SPONSOR_TYPE) VALUES
('SORDAC', 'SOF AT&L', 'CAPABILITY'),
('USSOCOM', 'USSOCOM', 'CAPABILITY'),
('SOF_ATL', 'SOF AT&L', 'POM'),
('USSOCOM_POM', 'USSOCOM POM', 'POM');

INSERT IGNORE INTO LOOKUP_ASSESSMENT_AREA (AREA_CODE, AREA_NAME, DESCRIPTION) VALUES
('RESEARCH_DEV', 'Research & Development', 'Research and Development activities'),
('ACQUISITION', 'Acquisition', 'Acquisition and procurement activities'),
('OPERATIONS', 'Operations', 'Operational activities'),
('MAINTENANCE', 'Maintenance', 'Maintenance and sustainment activities');

INSERT IGNORE INTO LOOKUP_RESOURCE_CATEGORY (CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION) VALUES
('RESEARCH_DEV', 'Research & Development', 'Research and Development activities'),
('ACQUISITION', 'Acquisition', 'Acquisition and procurement activities'),
('OPERATIONS', 'Operations', 'Operational activities'),
('MAINTENANCE', 'Maintenance', 'Maintenance and sustainment activities');
