<?php
/**
 * Part of ci-phpunit-test
 *
 * @author     Kenji Suzuki <https://github.com/kenjis>
 * @license    MIT License
 * @copyright  2015 Kenji Suzuki
 * @link       https://github.com/kenjis/ci-phpunit-test
 */

class DT_EXT_2024_seeder extends Seeder {

	private $table_1 = 'DT_EXT_2024';

	public function run()
	{
		$this->run_table_1();
	}

	private function run_table_1() {
		$this->db->truncate($this->table_1);

		$data = [
			'ADJUSTMENT_K' => 5906,
			'ASSESSMENT_AREA_CODE' => 'K',
			'BASE_K' => 1071,
			'BUDGET_ACTIVITY_CODE' => 'O',
			'BUDGET_ACTIVITY_NAME' => 'IWYJZBTPGACNSHRXVFQLEOMUDK',
			'BUDGET_SUB_ACTIVITY_CODE' => 'AS',
			'BUDGET_SUB_ACTIVITY_NAME' => 'PGFMYSXUNWZOAIQHVBKTCLJRDE',
			'CAPABILITY_SPONSOR_CODE' => 'TUXRPFMVWAJLD',
			'END_STRENGTH' => 9919,
			'EOC_CODE' => 'XRZWYUPTQCOAMSD',
			'EVENT_JUSTIFICATION' => 'ETNQLGPIJDSRWMFAXYHCOKBUZV',
			'EVENT_NAME' => 'USOPWXGMDIHAKRTQVELNYCFZJB',
			'EXECUTION_MANAGER_CODE' => 'INGRYUPWATBMK',
			'FISCAL_YEAR' => 1,
			'LINE_ITEM_CODE' => 'TQNIFYBGAHRCL',
			'OCO_OTHD_ADJUSTMENT_K' => 97,
			'OCO_OTHD_K' => 6540,
			'OCO_TO_BASE_K' => 8836,
			'OSD_PROGRAM_ELEMENT_CODE' => 'KQADZJHXPB',
			'POM_POSITION_CODE' => 'FDECMJIUT',
			'POM_SPONSOR_CODE' => 'IPGBFOCVUKTRW',
			'PROGRAM_CODE' => 'NICTORBPGUX',
			'PROGRAM_GROUP' => 'MWINBUCQJHOGX',
			'RDTE_PROJECT_CODE' => 'OVAJMCBY',
			'RESOURCE_CATEGORY_CODE' => 'ISBGZWPK',
			'RESOURCE_K' => 2464,
			'SPECIAL_PROJECT_CODE' => 1,
			'SUB_ACTIVITY_GROUP_CODE' => 'UCDS',
			'SUB_ACTIVITY_GROUP_NAME' => 'XDHKUBSZMWVGYROEPICANLJTFQ',
			'WORK_YEARS' => 9880,
		];

		$this->db->insert($this->table_1, $data);

		$data = [
			'ADJUSTMENT_K' => 9162,
			'ASSESSMENT_AREA_CODE' => 'O',
			'BASE_K' => 9304,
			'BUDGET_ACTIVITY_CODE' => 'E',
			'BUDGET_ACTIVITY_NAME' => 'KNZWPEFVGQXJLBSROHAIUMDTYC',
			'BUDGET_SUB_ACTIVITY_CODE' => 'MW',
			'BUDGET_SUB_ACTIVITY_NAME' => 'XJKFDUBGMCWPQAIVYLOHETNRSZ',
			'CAPABILITY_SPONSOR_CODE' => 'STPDGZWFRLYXB',
			'END_STRENGTH' => 9372,
			'EOC_CODE' => 'DCMXBERYGZTVQSU',
			'EVENT_JUSTIFICATION' => 'HIGYZOVLEXBKCJFSWUNQMRDTPA',
			'EVENT_NAME' => 'JHGDIWLVXSRPYTAMCEZOQBUNKF',
			'EXECUTION_MANAGER_CODE' => 'TISYEXQJZGUNK',
			'FISCAL_YEAR' => 1,
			'LINE_ITEM_CODE' => 'GSPOIBZTRUWAV',
			'OCO_OTHD_ADJUSTMENT_K' => 6345,
			'OCO_OTHD_K' => 8777,
			'OCO_TO_BASE_K' => 5147,
			'OSD_PROGRAM_ELEMENT_CODE' => 'AVOXDICKZP',
			'POM_POSITION_CODE' => 'OXIYKEMGC',
			'POM_SPONSOR_CODE' => 'PDNLCKYOWSRUB',
			'PROGRAM_CODE' => 'ESNFUQGIODT',
			'PROGRAM_GROUP' => 'GJDZIPYCWOMHQ',
			'RDTE_PROJECT_CODE' => 'CNZWLAXQ',
			'RESOURCE_CATEGORY_CODE' => 'JROQGSEU',
			'RESOURCE_K' => 1338,
			'SPECIAL_PROJECT_CODE' => 1,
			'SUB_ACTIVITY_GROUP_CODE' => 'YJBT',
			'SUB_ACTIVITY_GROUP_NAME' => 'CTXHLWYRFPOMEGIKVBQZDNJUAS',
			'WORK_YEARS' => 7202,
		];

		$this->db->insert($this->table_1, $data);

		$data = [
			'ADJUSTMENT_K' => 535,
			'ASSESSMENT_AREA_CODE' => 'O',
			'BASE_K' => 7787,
			'BUDGET_ACTIVITY_CODE' => 'E',
			'BUDGET_ACTIVITY_NAME' => 'KNZWPEFVGQXJLBSROHAIUMDTYC',
			'BUDGET_SUB_ACTIVITY_CODE' => 'MW',
			'BUDGET_SUB_ACTIVITY_NAME' => 'XJKFDUBGMCWPQAIVYLOHETNRSZ',
			'CAPABILITY_SPONSOR_CODE' => 'STPDGZWFRLYXB',
			'END_STRENGTH' => 2179,
			'EOC_CODE' => 'DCMXBERYGZTVQSU',
			'EVENT_JUSTIFICATION' => 'HIGYZOVLEXBKCJFSWUNQMRDTPA',
			'EVENT_NAME' => 'JHGDIWLVXSRPYTAMCEZOQBUNKF',
			'EXECUTION_MANAGER_CODE' => 'TISYEXQJZGUNK',
			'FISCAL_YEAR' => 1,
			'LINE_ITEM_CODE' => 'GSPOIBZTRUWAV',
			'OCO_OTHD_ADJUSTMENT_K' => 6592,
			'OCO_OTHD_K' => 3594,
			'OCO_TO_BASE_K' => 9150,
			'OSD_PROGRAM_ELEMENT_CODE' => 'AVOXDICKZP',
			'POM_POSITION_CODE' => 'OXIYKEMGC',
			'POM_SPONSOR_CODE' => 'PDNLCKYOWSRUB',
			'PROGRAM_CODE' => 'ESNFUQGIODT',
			'PROGRAM_GROUP' => 'GJDZIPYCWOMHQ',
			'RDTE_PROJECT_CODE' => 'CNZWLAXQ',
			'RESOURCE_CATEGORY_CODE' => 'JROQGSEU',
			'RESOURCE_K' => 6065,
			'SPECIAL_PROJECT_CODE' => 1,
			'SUB_ACTIVITY_GROUP_CODE' => 'YJBT',
			'SUB_ACTIVITY_GROUP_NAME' => 'CTXHLWYRFPOMEGIKVBQZDNJUAS',
			'WORK_YEARS' => 4141,
		];

		$this->db->insert($this->table_1, $data);

		$data = [
			'ADJUSTMENT_K' => 3563,
			'ASSESSMENT_AREA_CODE' => 'O',
			'BASE_K' => 5329,
			'BUDGET_ACTIVITY_CODE' => 'E',
			'BUDGET_ACTIVITY_NAME' => 'KNZWPEFVGQXJLBSROHAIUMDTYC',
			'BUDGET_SUB_ACTIVITY_CODE' => 'MW',
			'BUDGET_SUB_ACTIVITY_NAME' => 'XJKFDUBGMCWPQAIVYLOHETNRSZ',
			'CAPABILITY_SPONSOR_CODE' => 'STPDGZWFRLYXB',
			'END_STRENGTH' => 3451,
			'EOC_CODE' => 'DCMXBERYGZTVQSU',
			'EVENT_JUSTIFICATION' => 'HIGYZOVLEXBKCJFSWUNQMRDTPA',
			'EVENT_NAME' => 'JHGDIWLVXSRPYTAMCEZOQBUNKF',
			'EXECUTION_MANAGER_CODE' => 'TISYEXQJZGUNK',
			'FISCAL_YEAR' => 1,
			'LINE_ITEM_CODE' => 'GSPOIBZTRUWAV',
			'OCO_OTHD_ADJUSTMENT_K' => 8248,
			'OCO_OTHD_K' => 4494,
			'OCO_TO_BASE_K' => 8172,
			'OSD_PROGRAM_ELEMENT_CODE' => 'AVOXDICKZP',
			'POM_POSITION_CODE' => 'OXIYKEMGC',
			'POM_SPONSOR_CODE' => 'PDNLCKYOWSRUB',
			'PROGRAM_CODE' => 'ESNFUQGIODT',
			'PROGRAM_GROUP' => 'GJDZIPYCWOMHQ',
			'RDTE_PROJECT_CODE' => 'CNZWLAXQ',
			'RESOURCE_CATEGORY_CODE' => 'JROQGSEU',
			'RESOURCE_K' => 4452,
			'SPECIAL_PROJECT_CODE' => 1,
			'SUB_ACTIVITY_GROUP_CODE' => 'YJBT',
			'SUB_ACTIVITY_GROUP_NAME' => 'CTXHLWYRFPOMEGIKVBQZDNJUAS',
			'WORK_YEARS' => 1145,
		];

		$this->db->insert($this->table_1, $data);
	}
}
