<?php
/**
 * Part of ci-phpunit-test
 *
 * @author     Kenji Suzuki <https://github.com/kenjis>
 * @license    MIT License
 * @copyright  2015 Kenji Suzuki
 * @link       https://github.com/kenjis/ci-phpunit-test
 */

class DT_ISS_2024_seeder extends Seeder {

	private $table_1 = 'DT_ISS_2024';

	public function run()
	{
		$this->run_table_1();
	}

	private function run_table_1() {
		$this->db->truncate($this->table_1);

		$data = [
			'ADJUSTMENT_K' => 2170,
			'ASSESSMENT_AREA_CODE' => 'N',
			'BASE_K' => 5589,
			'BUDGET_ACTIVITY_CODE' => 'W',
			'BUDGET_ACTIVITY_NAME' => 'LWMXRYJIZEGBTVDAUNOQPHKFSC',
			'BUDGET_SUB_ACTIVITY_CODE' => 'JK',
			'BUDGET_SUB_ACTIVITY_NAME' => 'KHWATXMYDNQFLZUORSGPCJBVEI',
			'CAPABILITY_SPONSOR_CODE' => 'GELQPDYHNIROS',
			'END_STRENGTH' => 3606,
			'EOC_CODE' => 'ITXJQLZCSMBYADH',
			'EVENT_JUSTIFICATION' => 'GHDBTYNLZCIEOWKAMSPUXJQFRV',
			'EVENT_NAME' => 'LBSGMWTRUCIAZYHDFVJPXNOKQE',
			'EXECUTION_MANAGER_CODE' => 'OPVEGTUZNAMXW',
			'FISCAL_YEAR' => 1,
			'LINE_ITEM_CODE' => 'XMEVKISQWPOHC',
			'OCO_OTHD_ADJUSTMENT_K' => 5125,
			'OCO_OTHD_K' => 1042,
			'OCO_TO_BASE_K' => 3938,
			'OSD_PROGRAM_ELEMENT_CODE' => 'WSQHYEDMOX',
			'POM_POSITION_CODE' => 'TNEFCSUQK',
			'POM_SPONSOR_CODE' => 'ZXJDRGTIEBSNW',
			'PROGRAM_CODE' => 'NICTORBPGUX',
			'PROGRAM_GROUP' => 'MWINBUCQJHOGX',
			'RDTE_PROJECT_CODE' => 'GZALVTEF',
			'RESOURCE_CATEGORY_CODE' => 'ISBGZWPK',
			'RESOURCE_K' => 9126,
			'SPECIAL_PROJECT_CODE' => 1,
			'SUB_ACTIVITY_GROUP_CODE' => 'ALFR',
			'SUB_ACTIVITY_GROUP_NAME' => 'TBPYDNGKMUFQXLSIEZRACWOHJV',
			'WORK_YEARS' => 778,
		];

		$this->db->insert($this->table_1, $data);

		$data = [
			'ADJUSTMENT_K' => 1067,
			'ASSESSMENT_AREA_CODE' => 'C',
			'BASE_K' => 6494,
			'BUDGET_ACTIVITY_CODE' => 'F',
			'BUDGET_ACTIVITY_NAME' => 'SVJAFXWZPBCUKQTNLYMGHERDIO',
			'BUDGET_SUB_ACTIVITY_CODE' => 'GS',
			'BUDGET_SUB_ACTIVITY_NAME' => 'LDPXCNEMZJVFYIQBUARSKTHOWG',
			'CAPABILITY_SPONSOR_CODE' => 'OWXVZQUDYGPMH',
			'END_STRENGTH' => 3771,
			'EOC_CODE' => 'OJEUSHKYGDMNFPZ',
			'EVENT_JUSTIFICATION' => 'LVZPGRYJHUMECIWNQKFBAXDOST',
			'EVENT_NAME' => 'LTREYCKFUHMWOJQVXSZNIGPBAD',
			'EXECUTION_MANAGER_CODE' => 'JFODQHLCXVEBA',
			'FISCAL_YEAR' => 1,
			'LINE_ITEM_CODE' => 'RTWHNJZUDCYQA',
			'OCO_OTHD_ADJUSTMENT_K' => 3764,
			'OCO_OTHD_K' => 7768,
			'OCO_TO_BASE_K' => 7169,
			'OSD_PROGRAM_ELEMENT_CODE' => 'OFVQHTRLSM',
			'POM_POSITION_CODE' => 'ABOQSKYPX',
			'POM_SPONSOR_CODE' => 'CMZVTEXGYAFSN',
			'PROGRAM_CODE' => 'ESNFUQGIODT',
			'PROGRAM_GROUP' => 'GZWDPQOAEFYSB',
			'RDTE_PROJECT_CODE' => 'JYTKUWDP',
			'RESOURCE_CATEGORY_CODE' => 'JROQGSEU',
			'RESOURCE_K' => 1797,
			'SPECIAL_PROJECT_CODE' => 1,
			'SUB_ACTIVITY_GROUP_CODE' => 'UYTK',
			'SUB_ACTIVITY_GROUP_NAME' => 'LXPDHZOWKGSNYRTCUVQMEIJFBA',
			'WORK_YEARS' => 9205,
		];

		$this->db->insert($this->table_1, $data);

		$data = [
			'ADJUSTMENT_K' => 4623,
			'ASSESSMENT_AREA_CODE' => 'E',
			'BASE_K' => 7794,
			'BUDGET_ACTIVITY_CODE' => 'Y',
			'BUDGET_ACTIVITY_NAME' => 'FPTXYIRVKEMNUWZBHJGSDALQCO',
			'BUDGET_SUB_ACTIVITY_CODE' => 'XN',
			'BUDGET_SUB_ACTIVITY_NAME' => 'STJVDWLCKXYPIGNMEBHZAUOFRQ',
			'CAPABILITY_SPONSOR_CODE' => 'KJZITEFMHSYWR',
			'END_STRENGTH' => 6294,
			'EOC_CODE' => 'CLQXDZHNUEWKVAI',
			'EVENT_JUSTIFICATION' => 'EKGYACHLTXJVFSQRBNPDZMOIUW',
			'EVENT_NAME' => 'WSEDVQHYJICFKXUOARMGLBNTPZ',
			'EXECUTION_MANAGER_CODE' => 'JSOVPZNKWMFHA',
			'FISCAL_YEAR' => 1,
			'LINE_ITEM_CODE' => 'ZCLSKWGRUBAQF',
			'OCO_OTHD_ADJUSTMENT_K' => 8695,
			'OCO_OTHD_K' => 4443,
			'OCO_TO_BASE_K' => 8135,
			'OSD_PROGRAM_ELEMENT_CODE' => 'REWMUNBOXV',
			'POM_POSITION_CODE' => 'QBOKGRDXS',
			'POM_SPONSOR_CODE' => 'WTHBUOJYGNARP',
			'PROGRAM_CODE' => 'CLGVKWNUHBE',
			'PROGRAM_GROUP' => 'EMAFLITVUBXPZ',
			'RDTE_PROJECT_CODE' => 'QEVXPHCN',
			'RESOURCE_CATEGORY_CODE' => 'JZWQNYUH',
			'RESOURCE_K' => 886,
			'SPECIAL_PROJECT_CODE' => 1,
			'SUB_ACTIVITY_GROUP_CODE' => 'ZUEM',
			'SUB_ACTIVITY_GROUP_NAME' => 'CXVIPFWHUEDTLQGSYRJBNKAMOZ',
			'WORK_YEARS' => 4606,
		];

		$this->db->insert($this->table_1, $data);

		$data = [
			'ADJUSTMENT_K' => 4235,
			'ASSESSMENT_AREA_CODE' => 'U',
			'BASE_K' => 4527,
			'BUDGET_ACTIVITY_CODE' => 'H',
			'BUDGET_ACTIVITY_NAME' => 'VLCNMUAEQOIYBPJRZWXKSTFHGD',
			'BUDGET_SUB_ACTIVITY_CODE' => 'JG',
			'BUDGET_SUB_ACTIVITY_NAME' => 'TMKCFUOAJQRIXPZEBDYNSLHGVW',
			'CAPABILITY_SPONSOR_CODE' => 'AUHLJYDIMVXNG',
			'END_STRENGTH' => 2648,
			'EOC_CODE' => 'PDEQJBSFTYVCKAW',
			'EVENT_JUSTIFICATION' => 'CMDRYVSXOBKLNJQEHAWPGUZIFT',
			'EVENT_NAME' => 'LMCPZOVFRAQXJDGNIHEKWYTSUB',
			'EXECUTION_MANAGER_CODE' => 'LCHDNXMEFOGIZ',
			'FISCAL_YEAR' => 1,
			'LINE_ITEM_CODE' => 'RDMNBYXFVGITC',
			'OCO_OTHD_ADJUSTMENT_K' => 8893,
			'OCO_OTHD_K' => 8383,
			'OCO_TO_BASE_K' => 6186,
			'OSD_PROGRAM_ELEMENT_CODE' => 'FZCVHPYXAT',
			'POM_POSITION_CODE' => 'XZBVMSCGD',
			'POM_SPONSOR_CODE' => 'SXTGPBWNFHIJY',
			'PROGRAM_CODE' => 'CLGVKWNUHBE',
			'PROGRAM_GROUP' => 'EMAFLITVUBXPZ',
			'RDTE_PROJECT_CODE' => 'QMRNHWXC',
			'RESOURCE_CATEGORY_CODE' => 'JZWQNYUH',
			'RESOURCE_K' => 9359,
			'SPECIAL_PROJECT_CODE' => 1,
			'SUB_ACTIVITY_GROUP_CODE' => 'TZNC',
			'SUB_ACTIVITY_GROUP_NAME' => 'KWFSBJIGQCPYTDOXALURMZEVHN',
			'WORK_YEARS' => 9312,
		];

		$this->db->insert($this->table_1, $data);
	}
}
