<?php
/**
 * Part of ci-phpunit-test
 *
 * @author     Kenji Suzuki <https://github.com/kenjis>
 * @license    MIT License
 * @copyright  2015 Kenji Suzuki
 * @link       https://github.com/kenjis/ci-phpunit-test
 */

class DT_ZBT_2026_seeder extends Seeder {

	private $table_1 = 'DT_ZBT_2026';

	public function run()
	{
		$this->run_table_1();
	}

	private function run_table_1() {
		$this->db->truncate($this->table_1);

		$data = [
			'ADJUSTMENT_K' => 7259,
			'ASSESSMENT_AREA_CODE' => 'O',
			'BASE_K' => 8684,
			'BUDGET_ACTIVITY_CODE' => 'E',
			'BUDGET_ACTIVITY_NAME' => 'KNZWPEFVGQXJLBSROHAIUMDTYC',
			'BUDGET_SUB_ACTIVITY_CODE' => 'MW',
			'BUDGET_SUB_ACTIVITY_NAME' => 'XJKFDUBGMCWPQAIVYLOHETNRSZ',
			'CAPABILITY_SPONSOR_CODE' => 'STPDGZWFRLYXB',
			'END_STRENGTH' => 6992,
			'EOC_CODE' => 'DCMXBERYGZTVQSU',
			'EVENT_JUSTIFICATION' => 'HIGYZOVLEXBKCJFSWUNQMRDTPA',
			'EVENT_NAME' => 'JHGDIWLVXSRPYTAMCEZOQBUNKF',
			'EXECUTION_MANAGER_CODE' => 'TISYEXQJZGUNK',
			'FISCAL_YEAR' => 1,
			'LINE_ITEM_CODE' => 'GSPOIBZTRUWAV',
			'OCO_OTHD_ADJUSTMENT_K' => 6573,
			'OCO_OTHD_K' => 1763,
			'OCO_TO_BASE_K' => 3830,
			'OSD_PROGRAM_ELEMENT_CODE' => 'AVOXDICKZP',
			'POM_POSITION_CODE' => 'OXIYKEMGC',
			'POM_SPONSOR_CODE' => 'PDNLCKYOWSRUB',
			'PROGRAM_CODE' => 'ESNFUQGIODT',
			'PROGRAM_GROUP' => 'GJDZIPYCWOMHQ',
			'RDTE_PROJECT_CODE' => 'CNZWLAXQ',
			'RESOURCE_CATEGORY_CODE' => 'JROQGSEU',
			'RESOURCE_K' => 5518,
			'SPECIAL_PROJECT_CODE' => 1,
			'SUB_ACTIVITY_GROUP_CODE' => 'YJBT',
			'SUB_ACTIVITY_GROUP_NAME' => 'CTXHLWYRFPOMEGIKVBQZDNJUAS',
			'WORK_YEARS' => 9173,
		];

		$this->db->insert($this->table_1, $data);

		$data = [
			'ADJUSTMENT_K' => 9345,
			'ASSESSMENT_AREA_CODE' => 'O',
			'BASE_K' => 6333,
			'BUDGET_ACTIVITY_CODE' => 'E',
			'BUDGET_ACTIVITY_NAME' => 'KNZWPEFVGQXJLBSROHAIUMDTYC',
			'BUDGET_SUB_ACTIVITY_CODE' => 'MW',
			'BUDGET_SUB_ACTIVITY_NAME' => 'XJKFDUBGMCWPQAIVYLOHETNRSZ',
			'CAPABILITY_SPONSOR_CODE' => 'STPDGZWFRLYXB',
			'END_STRENGTH' => 2161,
			'EOC_CODE' => 'DCMXBERYGZTVQSU',
			'EVENT_JUSTIFICATION' => 'HIGYZOVLEXBKCJFSWUNQMRDTPA',
			'EVENT_NAME' => 'JHGDIWLVXSRPYTAMCEZOQBUNKF',
			'EXECUTION_MANAGER_CODE' => 'TISYEXQJZGUNK',
			'FISCAL_YEAR' => 1,
			'LINE_ITEM_CODE' => 'GSPOIBZTRUWAV',
			'OCO_OTHD_ADJUSTMENT_K' => 6649,
			'OCO_OTHD_K' => 2845,
			'OCO_TO_BASE_K' => 8191,
			'OSD_PROGRAM_ELEMENT_CODE' => 'AVOXDICKZP',
			'POM_POSITION_CODE' => 'OXIYKEMGC',
			'POM_SPONSOR_CODE' => 'PDNLCKYOWSRUB',
			'PROGRAM_CODE' => 'ESNFUQGIODT',
			'PROGRAM_GROUP' => 'GJDZIPYCWOMHQ',
			'RDTE_PROJECT_CODE' => 'CNZWLAXQ',
			'RESOURCE_CATEGORY_CODE' => 'JROQGSEU',
			'RESOURCE_K' => 8667,
			'SPECIAL_PROJECT_CODE' => 1,
			'SUB_ACTIVITY_GROUP_CODE' => 'YJBT',
			'SUB_ACTIVITY_GROUP_NAME' => 'CTXHLWYRFPOMEGIKVBQZDNJUAS',
			'WORK_YEARS' => 7923,
		];

		$this->db->insert($this->table_1, $data);
	}
}
