<?php
/**
 * Part of ci-phpunit-test
 *
 * @author     Kenji Suzuki <https://github.com/kenjis>
 * @license    MIT License
 * @copyright  2015 Kenji Suzuki
 * @link       https://github.com/kenjis/ci-phpunit-test
 */

class SOCOM_model_seeder extends Seeder {

	private $table_1 = 'DT_ZBT_EXTRACT_2026';
	private $table_2 = 'LOOKUP_RESOURCE_CATEGORY';
	private $table_3 = 'LOOKUP_PROGRAM';
	private $table_4 = 'DT_ISS_2026';

	public function run()
	{
		$this->run_table_1();
		$this->run_table_2();
		$this->run_table_3();
		$this->run_table_4();
	}

	private function run_table_1() {
		$this->db->truncate($this->table_1);

		$data = [
			'ASSESSMENT_AREA_CODE' => 'K',
			'BUDGET_ACTIVITY_CODE' => 'O',
			'BUDGET_ACTIVITY_NAME' => 'IWYJZBTPGACNSHRXVFQLEOMUDK',
			'BUDGET_SUB_ACTIVITY_CODE' => 'AS',
			'BUDGET_SUB_ACTIVITY_NAME' => 'PGFMYSXUNWZOAIQHVBKTCLJRDE',
			'CAPABILITY_SPONSOR_CODE' => 'TUXRPFMVWAJLD',
			'DELTA_AMT' => 1333,
			'DELTA_O2B_AMT' => 815,
			'DELTA_OCO_AMT' => 3283,
			'EOC_CODE' => 'XRZWYUPTQCOAMSD',
			'EVENT_DATE' => '2031-03-13 01:21:56',
			'EVENT_JUSTIFICATION' => 'ETNQLGPIJDSRWMFAXYHCOKBUZV',
			'EVENT_NAME' => 'USOPWXGMDIHAKRTQVELNYCFZJB',
			'EVENT_STATUS' => 'JOYCBQZWSXKRHFVEUMLIA',
			'EVENT_STATUS_COMMENT' => 'VPOAEUQNFYCRLMSWZIJDXHBTGK',
			'EVENT_TITLE' => 'YVMCWHAKGXPTFUNOJEQLDRBSZI',
			'EVENT_TYPE' => 'PJN',
			'EVENT_USER' => 'LXTMDOCKIWAVNUBRSZEFQPYHJG',
			'EXECUTION_MANAGER_CODE' => 'INGRYUPWATBMK',
			'FISCAL_YEAR' => 1,
			'LINE_ITEM_CODE' => 'QDSLVEAORWHCK',
			'O2B_AMT' => 1536,
			'OCO_AMT' => 1965,
			'OSD_PROGRAM_ELEMENT_CODE' => 'KQADZJHXPB',
			'POM_POSITION_CODE' => 'FDECMJIUT',
			'POM_SPONSOR_CODE' => 'IPGBFOCVUKTRW',
			'PROGRAM_CODE' => 'NICTORBPGUX',
			'PROGRAM_GROUP' => 'MWINBUCQJHOGX',
			'PROP_AMT' => 3633,
			'PROP_O2B_AMT' => 4311,
			'PROP_OCO_AMT' => 4985,
			'RDTE_PROJECT_CODE' => 'OVAJMCBY',
			'RESOURCE_CATEGORY_CODE' => 'ISBGZWPK',
			'RESOURCE_K' => 8027,
			'SPECIAL_PROJECT_CODE' => 1,
			'SUB_ACTIVITY_GROUP_CODE' => 'UCDS',
			'SUB_ACTIVITY_GROUP_NAME' => 'XDHKUBSZMWVGYROEPICANLJTFQ',
		];
		$this->db->insert($this->table_1, $data);
		
		$data = [
			'ASSESSMENT_AREA_CODE' => 'O',
			'BUDGET_ACTIVITY_CODE' => 'E',
			'BUDGET_ACTIVITY_NAME' => 'KNZWPEFVGQXJLBSROHAIUMDTYC',
			'BUDGET_SUB_ACTIVITY_CODE' => 'MW',
			'BUDGET_SUB_ACTIVITY_NAME' => 'XJKFDUBGMCWPQAIVYLOHETNRSZ',
			'CAPABILITY_SPONSOR_CODE' => 'STPDGZWFRLYXB',
			'DELTA_AMT' => 1472,
			'DELTA_O2B_AMT' => 8349,
			'DELTA_OCO_AMT' => 5890,
			'EOC_CODE' => 'DCMXBERYGZTVQSU',
			'EVENT_DATE' => '2056-07-07 08:16:21',
			'EVENT_JUSTIFICATION' => 'HIGYZOVLEXBKCJFSWUNQMRDTPA',
			'EVENT_NAME' => 'JHGDIWLVXSRPYTAMCEZOQBUNKF',
			'EVENT_STATUS' => 'JKCBFUAZPGTMDHENOLYRW',
			'EVENT_STATUS_COMMENT' => 'ANORMUFDKPWCGTLIEXJBQVZSYH',
			'EVENT_TITLE' => 'GEXJQZPRDSOHMTYCUIBAKLNWFV',
			'EVENT_TYPE' => 'UIO',
			'EVENT_USER' => 'LIJKYGUBTZHCXSVDWPFQMRNAOE',
			'EXECUTION_MANAGER_CODE' => 'TISYEXQJZGUNK',
			'FISCAL_YEAR' => 1,
			'LINE_ITEM_CODE' => 'GSPOIBZTRUWAV',
			'O2B_AMT' => 3944,
			'OCO_AMT' => 9345,
			'OSD_PROGRAM_ELEMENT_CODE' => 'AVOXDICKZP',
			'POM_POSITION_CODE' => 'OXIYKEMGC',
			'POM_SPONSOR_CODE' => 'PDNLCKYOWSRUB',
			'PROGRAM_CODE' => 'ESNFUQGIODT',
			'PROGRAM_GROUP' => 'GJDZIPYCWOMHQ',
			'PROP_AMT' => 9398,
			'PROP_O2B_AMT' => 659,
			'PROP_OCO_AMT' => 4622,
			'RDTE_PROJECT_CODE' => 'CNZWLAXQ',
			'RESOURCE_CATEGORY_CODE' => 'JROQGSEU',
			'RESOURCE_K' => 6829,
			'SPECIAL_PROJECT_CODE' => 1,
			'SUB_ACTIVITY_GROUP_CODE' => 'YJBT',
			'SUB_ACTIVITY_GROUP_NAME' => 'CTXHLWYRFPOMEGIKVBQZDNJUAS',
		];
		$this->db->insert($this->table_1, $data);
		
		$data = [
			'ASSESSMENT_AREA_CODE' => 'J',
			'BUDGET_ACTIVITY_CODE' => 'Y',
			'BUDGET_ACTIVITY_NAME' => 'VWMBCJDKUGREIPLFXHOSNATYZQ',
			'BUDGET_SUB_ACTIVITY_CODE' => 'WP',
			'BUDGET_SUB_ACTIVITY_NAME' => 'ZXTGEYOUNKIAVBRPSMDQWFCJLH',
			'CAPABILITY_SPONSOR_CODE' => 'IEDKOVTJGLZXN',
			'DELTA_AMT' => 3828,
			'DELTA_O2B_AMT' => 8898,
			'DELTA_OCO_AMT' => 338,
			'EOC_CODE' => 'HNZGFOXELDMTCSY',
			'EVENT_DATE' => '2033-06-06 06:03:50',
			'EVENT_JUSTIFICATION' => 'IJSEVARGUQCTNBFLOZYPXHWMKD',
			'EVENT_NAME' => 'WZVMQCPTIKJHARGXUBSNYELDOF',
			'EVENT_STATUS' => 'LXAPIRFSTDZWNUOCVKQYE',
			'EVENT_STATUS_COMMENT' => 'UNJLKGZXRDTOCBFQVYPIWHMESA',
			'EVENT_TITLE' => 'XUDSVJKIEFLCWHYRTZAOBMNPQG',
			'EVENT_TYPE' => 'LIO',
			'EVENT_USER' => 'ASQZLDOEHUPYKNGBMJVFTWRICX',
			'EXECUTION_MANAGER_CODE' => 'FEPWOTIRZKYMV',
			'FISCAL_YEAR' => 1,
			'LINE_ITEM_CODE' => 'CKULPHGAIVOQN',
			'O2B_AMT' => 4638,
			'OCO_AMT' => 4854,
			'OSD_PROGRAM_ELEMENT_CODE' => 'OQNHBAIMXL',
			'POM_POSITION_CODE' => 'EPLHKZGAD',
			'POM_SPONSOR_CODE' => 'LFNJWPHDGBIAR',
			'PROGRAM_CODE' => 'CLGVKWNUHBE',
			'PROGRAM_GROUP' => 'EMAFLITVUBXPZ',
			'PROP_AMT' => 678,
			'PROP_O2B_AMT' => 3670,
			'PROP_OCO_AMT' => 1453,
			'RDTE_PROJECT_CODE' => 'MHLUTOWY',
			'RESOURCE_CATEGORY_CODE' => 'JZWQNYUH',
			'RESOURCE_K' => 9478,
			'SPECIAL_PROJECT_CODE' => 1,
			'SUB_ACTIVITY_GROUP_CODE' => 'XFZQ',
			'SUB_ACTIVITY_GROUP_NAME' => 'WOVKLSENRUTXGBQCYZHDJFAIMP',
		];
		$this->db->insert($this->table_1, $data);
	}

	private function run_table_2() {
		$this->db->truncate($this->table_2);

		$data = [
			'RESOURCE_CATEGORY_CODE' => 'ISBGZWPK',
			'RESOURCE_CATEGORY' => 'FENYQTUXJRMCSPAVWZGODBHILK',
			'UNIT' => 'JMYAQSKUBCORPGNWHXDF',
		];

		$this->db->insert($this->table_2, $data);

		$data = [
			'RESOURCE_CATEGORY_CODE' => 'JROQGSEU',
			'RESOURCE_CATEGORY' => 'HSGQMRNXJBTZKDFOPWYEILVACU',
			'UNIT' => 'COLVRBAMZYEWUXJHTGFQ',
		];

		$this->db->insert($this->table_2, $data);

		$data = [
			'RESOURCE_CATEGORY_CODE' => 'JZWQNYUH',
			'RESOURCE_CATEGORY' => 'YTFXLUSDRQJMBIOPZCGNHKWEVA',
			'UNIT' => 'VMWOJKFHRSQIDPZGUYAB',
		];

		$this->db->insert($this->table_2, $data);

		$data = [
			'RESOURCE_CATEGORY_CODE' => 'JZWQNYUH',
			'RESOURCE_CATEGORY' => 'IJKYPLSEWTVOXUQZBCRHDMNAFG',
			'UNIT' => 'AECDNWZKPOYGUVXLBRMF',
		];

		$this->db->insert($this->table_2, $data);
	}

	private function run_table_3() {
		$this->db->truncate($this->table_3);

		$data = [
			'ID' => 'AHOSVZIPQURWTECBJMKYDLGXNF',
			'PROGRAM_GROUP' => 'MWINBUCQJHOGX',
			'PROGRAM_CODE' => 'NICTORBPGUX',
			'PROGRAM_NAME' => 'EOYTGIAZWDKFJNSCRVLUBQXHPM',
			'PROGRAM_TYPE_CODE' => 'Q',
			'PROGRAM_SUB_TYPE_CODE' => 'EXJCK',
			'PROGRAM_DESCRIPTION' => 'RKIHOLNEFYVWAGMCBUZPQSXJDT',
			'CAPABILITY_SPONSOR_CODE' => 'JRYCESMPBKNWU',
			'ASSESSMENT_AREA_CODE' => 'Z',
			'POM_SPONSOR_CODE' => 'QWBJLUTVZXYFI',
			'JCA_LV1_ID' => 'EUVW',
			'JCA_LV2_ID' => 'XGLOK',
			'JCA_LV3_ID' => 'XNIFZH',
			'STORM_ID' => 'JUZGVPEMAXLSWHTQONKFRCYIB',
		];

		$this->db->insert($this->table_3, $data);

		$data = [
			'ID' => 'NMLYJXCKTAPDHOWIVZGFQBSURE',
			'PROGRAM_GROUP' => 'GJDZIPYCWOMHQ',
			'PROGRAM_CODE' => 'ESNFUQGIODT',
			'PROGRAM_NAME' => 'KPOBFZJIXWMCDYSNEULQGAVTRH',
			'PROGRAM_TYPE_CODE' => 'S',
			'PROGRAM_SUB_TYPE_CODE' => 'CESWT',
			'PROGRAM_DESCRIPTION' => 'RGUEXTBSFAJCYMQKZPNILHOWVD',
			'CAPABILITY_SPONSOR_CODE' => 'LWITUDHXPGZOF',
			'ASSESSMENT_AREA_CODE' => 'N',
			'POM_SPONSOR_CODE' => 'ICBWXVJHZADUN',
			'JCA_LV1_ID' => 'DRHZ',
			'JCA_LV2_ID' => 'JPVNT',
			'JCA_LV3_ID' => 'IHFXKQ',
			'STORM_ID' => 'UKTSYXJDGAHMQROWPLEFBIZNC',
		];

		$this->db->insert($this->table_3, $data);

		$data = [
			'ID' => 'KVMLIXHZTDAEUQFCJRBOWSPYNG',
			'PROGRAM_GROUP' => 'EMAFLITVUBXPZ',
			'PROGRAM_CODE' => 'CLGVKWNUHBE',
			'PROGRAM_NAME' => 'LUNBCVHSMJQTWDOYKPREXZAFGI',
			'PROGRAM_TYPE_CODE' => 'M',
			'PROGRAM_SUB_TYPE_CODE' => 'OBZNV',
			'PROGRAM_DESCRIPTION' => 'PNEGKQTDBYFZSMAJVCRIHOUWXL',
			'CAPABILITY_SPONSOR_CODE' => 'MPAWYDSVZHITU',
			'ASSESSMENT_AREA_CODE' => 'W',
			'POM_SPONSOR_CODE' => 'YVTRNICZBDJEA',
			'JCA_LV1_ID' => 'UCVN',
			'JCA_LV2_ID' => 'MDIGV',
			'JCA_LV3_ID' => 'PWGNTK',
			'STORM_ID' => 'ZHMLQIXTWPONASGEVKJUDBFCY',
		];

		$this->db->insert($this->table_3, $data);

		$data = [
			'ID' => 'WMZFRQHAVSDTGCBYPEJUNLKIXO',
			'PROGRAM_GROUP' => 'EMAFLITVUBXPZ',
			'PROGRAM_CODE' => 'CLGVKWNUHBE',
			'PROGRAM_NAME' => 'HMFYDVOWLXICREJUNQZPBSKATG',
			'PROGRAM_TYPE_CODE' => 'J',
			'PROGRAM_SUB_TYPE_CODE' => 'TMEIB',
			'PROGRAM_DESCRIPTION' => 'HBQAMDENRCUPYKTOWSLFGXIJZV',
			'CAPABILITY_SPONSOR_CODE' => 'ONTLGQZWBFHAS',
			'ASSESSMENT_AREA_CODE' => 'U',
			'POM_SPONSOR_CODE' => 'ODUPXTBHLQVAM',
			'JCA_LV1_ID' => 'VPKX',
			'JCA_LV2_ID' => 'TWGZN',
			'JCA_LV3_ID' => 'EBWZFK',
			'STORM_ID' => 'MFHUWVCDZBAJNPGOLIRESTYXQ',
		];

		$this->db->insert($this->table_3, $data);
	}

	private function run_table_4() {
		$this->db->truncate($this->table_4);

		$data = [
			'ADJUSTMENT_K' => 2170,
			'ASSESSMENT_AREA_CODE' => 'N',
			'BASE_K' => 5589,
			'BUDGET_ACTIVITY_CODE' => 'W',
			'BUDGET_ACTIVITY_NAME' => 'LWMXRYJIZEGBTVDAUNOQPHKFSC',
			'BUDGET_SUB_ACTIVITY_CODE' => 'JK',
			'BUDGET_SUB_ACTIVITY_NAME' => 'KHWATXMYDNQFLZUORSGPCJBVEI',
			'CAPABILITY_SPONSOR_CODE' => 'GELQPDYHNIROS',
			'END_STRENGTH' => 3606,
			'EOC_CODE' => 'ITXJQLZCSMBYADH',
			'EVENT_JUSTIFICATION' => 'GHDBTYNLZCIEOWKAMSPUXJQFRV',
			'EVENT_NAME' => 'LBSGMWTRUCIAZYHDFVJPXNOKQE',
			'EXECUTION_MANAGER_CODE' => 'OPVEGTUZNAMXW',
			'FISCAL_YEAR' => 1,
			'LINE_ITEM_CODE' => 'XMEVKISQWPOHC',
			'OCO_OTHD_ADJUSTMENT_K' => 5125,
			'OCO_OTHD_K' => 1042,
			'OCO_TO_BASE_K' => 3938,
			'OSD_PROGRAM_ELEMENT_CODE' => 'WSQHYEDMOX',
			'POM_POSITION_CODE' => 'TNEFCSUQK',
			'POM_SPONSOR_CODE' => 'ZXJDRGTIEBSNW',
			'PROGRAM_CODE' => 'NICTORBPGUX',
			'PROGRAM_GROUP' => 'MWINBUCQJHOGX',
			'RDTE_PROJECT_CODE' => 'GZALVTEF',
			'RESOURCE_CATEGORY_CODE' => 'ISBGZWPK',
			'RESOURCE_K' => 9126,
			'SPECIAL_PROJECT_CODE' => 1,
			'SUB_ACTIVITY_GROUP_CODE' => 'ALFR',
			'SUB_ACTIVITY_GROUP_NAME' => 'TBPYDNGKMUFQXLSIEZRACWOHJV',
			'WORK_YEARS' => 778,
		];

		$this->db->insert($this->table_4, $data);

		$data = [
			'ADJUSTMENT_K' => 1067,
			'ASSESSMENT_AREA_CODE' => 'C',
			'BASE_K' => 6494,
			'BUDGET_ACTIVITY_CODE' => 'F',
			'BUDGET_ACTIVITY_NAME' => 'SVJAFXWZPBCUKQTNLYMGHERDIO',
			'BUDGET_SUB_ACTIVITY_CODE' => 'GS',
			'BUDGET_SUB_ACTIVITY_NAME' => 'LDPXCNEMZJVFYIQBUARSKTHOWG',
			'CAPABILITY_SPONSOR_CODE' => 'OWXVZQUDYGPMH',
			'END_STRENGTH' => 3771,
			'EOC_CODE' => 'OJEUSHKYGDMNFPZ',
			'EVENT_JUSTIFICATION' => 'LVZPGRYJHUMECIWNQKFBAXDOST',
			'EVENT_NAME' => 'LTREYCKFUHMWOJQVXSZNIGPBAD',
			'EXECUTION_MANAGER_CODE' => 'JFODQHLCXVEBA',
			'FISCAL_YEAR' => 1,
			'LINE_ITEM_CODE' => 'RTWHNJZUDCYQA',
			'OCO_OTHD_ADJUSTMENT_K' => 3764,
			'OCO_OTHD_K' => 7768,
			'OCO_TO_BASE_K' => 7169,
			'OSD_PROGRAM_ELEMENT_CODE' => 'OFVQHTRLSM',
			'POM_POSITION_CODE' => 'ABOQSKYPX',
			'POM_SPONSOR_CODE' => 'CMZVTEXGYAFSN',
			'PROGRAM_CODE' => 'ESNFUQGIODT',
			'PROGRAM_GROUP' => 'GZWDPQOAEFYSB',
			'RDTE_PROJECT_CODE' => 'JYTKUWDP',
			'RESOURCE_CATEGORY_CODE' => 'JROQGSEU',
			'RESOURCE_K' => 1797,
			'SPECIAL_PROJECT_CODE' => 1,
			'SUB_ACTIVITY_GROUP_CODE' => 'UYTK',
			'SUB_ACTIVITY_GROUP_NAME' => 'LXPDHZOWKGSNYRTCUVQMEIJFBA',
			'WORK_YEARS' => 9205,
		];

		$this->db->insert($this->table_4, $data);

		$data = [
			'ADJUSTMENT_K' => 4623,
			'ASSESSMENT_AREA_CODE' => 'E',
			'BASE_K' => 7794,
			'BUDGET_ACTIVITY_CODE' => 'Y',
			'BUDGET_ACTIVITY_NAME' => 'FPTXYIRVKEMNUWZBHJGSDALQCO',
			'BUDGET_SUB_ACTIVITY_CODE' => 'XN',
			'BUDGET_SUB_ACTIVITY_NAME' => 'STJVDWLCKXYPIGNMEBHZAUOFRQ',
			'CAPABILITY_SPONSOR_CODE' => 'KJZITEFMHSYWR',
			'END_STRENGTH' => 6294,
			'EOC_CODE' => 'CLQXDZHNUEWKVAI',
			'EVENT_JUSTIFICATION' => 'EKGYACHLTXJVFSQRBNPDZMOIUW',
			'EVENT_NAME' => 'WSEDVQHYJICFKXUOARMGLBNTPZ',
			'EXECUTION_MANAGER_CODE' => 'JSOVPZNKWMFHA',
			'FISCAL_YEAR' => 1,
			'LINE_ITEM_CODE' => 'ZCLSKWGRUBAQF',
			'OCO_OTHD_ADJUSTMENT_K' => 8695,
			'OCO_OTHD_K' => 4443,
			'OCO_TO_BASE_K' => 8135,
			'OSD_PROGRAM_ELEMENT_CODE' => 'REWMUNBOXV',
			'POM_POSITION_CODE' => 'QBOKGRDXS',
			'POM_SPONSOR_CODE' => 'WTHBUOJYGNARP',
			'PROGRAM_CODE' => 'CLGVKWNUHBE',
			'PROGRAM_GROUP' => 'EMAFLITVUBXPZ',
			'RDTE_PROJECT_CODE' => 'QEVXPHCN',
			'RESOURCE_CATEGORY_CODE' => 'JZWQNYUH',
			'RESOURCE_K' => 886,
			'SPECIAL_PROJECT_CODE' => 1,
			'SUB_ACTIVITY_GROUP_CODE' => 'ZUEM',
			'SUB_ACTIVITY_GROUP_NAME' => 'CXVIPFWHUEDTLQGSYRJBNKAMOZ',
			'WORK_YEARS' => 4606,
		];

		$this->db->insert($this->table_4, $data);

		$data = [
			'ADJUSTMENT_K' => 4235,
			'ASSESSMENT_AREA_CODE' => 'U',
			'BASE_K' => 4527,
			'BUDGET_ACTIVITY_CODE' => 'H',
			'BUDGET_ACTIVITY_NAME' => 'VLCNMUAEQOIYBPJRZWXKSTFHGD',
			'BUDGET_SUB_ACTIVITY_CODE' => 'JG',
			'BUDGET_SUB_ACTIVITY_NAME' => 'TMKCFUOAJQRIXPZEBDYNSLHGVW',
			'CAPABILITY_SPONSOR_CODE' => 'AUHLJYDIMVXNG',
			'END_STRENGTH' => 2648,
			'EOC_CODE' => 'PDEQJBSFTYVCKAW',
			'EVENT_JUSTIFICATION' => 'CMDRYVSXOBKLNJQEHAWPGUZIFT',
			'EVENT_NAME' => 'LMCPZOVFRAQXJDGNIHEKWYTSUB',
			'EXECUTION_MANAGER_CODE' => 'LCHDNXMEFOGIZ',
			'FISCAL_YEAR' => 1,
			'LINE_ITEM_CODE' => 'RDMNBYXFVGITC',
			'OCO_OTHD_ADJUSTMENT_K' => 8893,
			'OCO_OTHD_K' => 8383,
			'OCO_TO_BASE_K' => 6186,
			'OSD_PROGRAM_ELEMENT_CODE' => 'FZCVHPYXAT',
			'POM_POSITION_CODE' => 'XZBVMSCGD',
			'POM_SPONSOR_CODE' => 'SXTGPBWNFHIJY',
			'PROGRAM_CODE' => 'CLGVKWNUHBE',
			'PROGRAM_GROUP' => 'EMAFLITVUBXPZ',
			'RDTE_PROJECT_CODE' => 'QMRNHWXC',
			'RESOURCE_CATEGORY_CODE' => 'JZWQNYUH',
			'RESOURCE_K' => 9359,
			'SPECIAL_PROJECT_CODE' => 1,
			'SUB_ACTIVITY_GROUP_CODE' => 'TZNC',
			'SUB_ACTIVITY_GROUP_NAME' => 'KWFSBJIGQCPYTDOXALURMZEVHN',
			'WORK_YEARS' => 9312,
		];

		$this->db->insert($this->table_4, $data);
	}
}
